# Generated by Django 4.1.7 on 2023-04-09 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('member', 'member')], max_length=255)),
                ('password', models.TextField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
