# Generated by Django 4.1.7 on 2023-09-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_excluded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
