# Generated by Django 4.1.7 on 2023-09-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='critical_feedback_prompt',
            field=models.TextField(blank=True, default='NOTE: Evaluate the candidate answer in a very strict manner and provide a critical feedback.', null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='critical_skill_prompt',
            field=models.TextField(blank=True, default='NOTE: Evaluate the answers from a very critical perspective and rate the skills.', null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='custom_feedback_prompt_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='custom_feedback_prompt_2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='custom_skill_prompt_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='custom_skill_prompt_2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='difficulty_level',
            field=models.CharField(blank=True, default='Midium', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='easy_feedback_prompt',
            field=models.TextField(blank=True, default='NOTE: Evaluate the candidate answer from a very liberal perspective and provide feedback in a friendly manner.', null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='easy_skill_prompt',
            field=models.TextField(blank=True, default='NOTE: Evaluate the answers from a very liberal perspective and rate the skills.', null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='midium_feedback_prompt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='midium_skill_prompt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
