# Generated by Django 4.1.7 on 2023-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userattribute_critical_feedback_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='test_previlage',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
