# Generated by Django 4.1.7 on 2023-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userattribute_test_previlage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member'), ('client_admin', 'client admin')], max_length=255),
        ),
    ]
