# Generated by Django 4.1.7 on 2024-01-02 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignatureBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.PositiveSmallIntegerField(default=0)),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("bot_id", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                (
                    "tag",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=None, null=True)),
                ("data", models.JSONField(blank=True, default=None, null=True)),
                ("prompt", models.TextField(blank=True, default=None, null=True)),
                (
                    "custom_prompt",
                    models.TextField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "db_table": "signature_bot",
                "unique_together": {("tenant_id", "user_id", "tag")},
            },
        ),
    ]
