# Generated by Django 4.1.7 on 2024-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_signaturebot"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturebot",
            name="bot_type",
            field=models.CharField(
                blank=True, default="coaching", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="signaturebot",
            name="faqs",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
