# Generated by Django 4.1.7 on 2024-01-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_signaturebot_bot_type_signaturebot_faqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturebot",
            name="bot_details",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="signaturebot",
            name="recommended_codes",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
