# Generated by Django 4.1.7 on 2024-01-10 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_signaturebot_bot_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('bot_id', models.CharField(max_length=255)),
                ('bot_name', models.CharField(max_length=255)),
                ('coach_name', models.CharField(max_length=255)),
                ('coach_email', models.CharField(max_length=255)),
                ('attached_data', models.TextField(blank=True, default=None, null=True)),
                ('attached_links', models.TextField(blank=True, default=None, null=True)),
                ('client_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conversations_per_month', models.IntegerField(blank=True, default=None, null=True)),
                ('fitment_answers', models.JSONField(blank=True, default=None, null=True)),
                ('fitment_data', models.JSONField(blank=True, default=None, null=True)),
                ('feedback_questions', models.JSONField(blank=True, default=None, null=True)),
                ('attached_files', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
            options={
                'db_table': 'bot_attributes',
                'unique_together': {('tenant_id', 'bot_id')},
            },
        ),
    ]
