# Generated by Django 4.1.7 on 2024-01-10 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_botattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('owner_id', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, default=None, null=True)),
                ('member_emails', models.TextField(blank=True, default=None, null=True)),
                ('member_mob_numbers', models.TextField(blank=True, default=None, null=True)),
                ('member_user_ids', models.TextField(blank=True, default=None, null=True)),
                ('avatar_bot_creation', models.BooleanField(default=False, null=True)),
                ('feedback_bot_creation', models.BooleanField(default=False, null=True)),
                ('subject_matter_bot_creation', models.BooleanField(default=False, null=True)),
                ('number_of_creation_per_month', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'client_user_info',
                'unique_together': {('tenant_id', 'client_name')},
            },
        ),
    ]
