# Generated by Django 4.1.7 on 2024-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_clientuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='botattribute',
            name='attached_faqs_context',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
