# Generated by Django 4.1.7 on 2024-01-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_botattribute_attached_faqs_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='botattribute',
            name='initial_qnas',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
