# Generated by Django 4.1.7 on 2024-01-13 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_botattribute_attached_faqs_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachCoacheeMentorMenteeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.PositiveSmallIntegerField(default=0)),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("coach", "coach"),
                            ("coachee", "coachee"),
                            ("mentor", "mentor"),
                            ("mentee", "mentee"),
                        ],
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "speciality",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "favourite_simulation_codes",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("about", models.TextField(blank=True, default=None, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("bot_ids", models.TextField(blank=True, default=None, null=True)),
                ("bot_urls", models.TextField(blank=True, default=None, null=True)),
                (
                    "profile_image_url",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "coach_coachee_mentor_mentee_profile",
                "unique_together": {("tenant_id", "uid")},
            },
        ),
    ]
