# Generated by Django 4.1.7 on 2024-01-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_botattribute_initial_qnas'),
        ('users', '0014_coachcoacheementormenteeprofile'),
    ]

    operations = [
    ]
