# Generated by Django 4.1.7 on 2024-01-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_coachcoacheementormenteeprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="admired_leaders",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="area_domain",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="coach_same_department",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="coaching_for_fitment",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="coaching_level",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="coaching_style",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="dominant_point_of_view",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="hard_skill_areas",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="high_rating_characteristics",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="is_approved",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="low_rating_characteristics",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="mentoring_frameworks",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="mentoring_preferences",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="other_details",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="problem_solving_approach",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="provided_links",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="supported_outcome",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="time_commitment",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="coachcoacheementormenteeprofile",
            name="voice_sample",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
