# Generated by Django 4.1.7 on 2024-01-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20240117_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientuserinfo',
            old_name='number_of_creation_per_month',
            new_name='number_of_conversation_per_month',
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='required_form_fields',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='signaturebot',
            name='is_fitment_analysis',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
