# Generated by Django 4.1.7 on 2024-01-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_coachcoacheementormenteeprofile_admired_leaders_and_more"),
        ("users", "0015_merge_20240117_1148"),
    ]

    operations = []
