# Generated by Django 4.1.7 on 2024-01-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20240117_1246'),
        ('users', '0016_rename_number_of_creation_per_month_clientuserinfo_number_of_conversation_per_month_and_more'),
    ]

    operations = [
    ]
