# Generated by Django 4.1.7 on 2024-01-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20240117_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='is_strict_fitment',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
