# Generated by Django 4.1.7 on 2024-01-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_signaturebot_is_strict_fitment"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturebot",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="signaturebot",
            name="is_approved",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="signaturebot",
            name="is_sample_bot",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="signaturebot",
            name="is_system_bot",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
