# Generated by Django 4.1.7 on 2024-01-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_signaturebot_is_active_signaturebot_is_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturebot",
            name="use_google_context",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
