# Generated by Django 4.1.7 on 2024-01-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_signaturebot_use_google_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='demo_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='restricted_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
