# Generated by Django 4.1.7 on 2024-01-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_clientuserinfo_demo_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botattribute',
            name='is_audio_response',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
