# Generated by Django 4.1.7 on 2024-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_botattribute_is_audio_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaturebot",
            name="bot_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coach", "coach"),
                    ("coachee", "coachee"),
                    ("mentor", "mentor"),
                    ("mentee", "mentee"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
