# Generated by Django 4.1.7 on 2024-01-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_signaturebot_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='competency_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
