# Generated by Django 4.1.7 on 2024-01-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userattribute_competency_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='bot_snippets',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
