# Generated by Django 4.1.7 on 2024-01-23 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_coachcoacheementormenteeprofile_bot_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='mob_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BotAndUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('bot_id', models.CharField(max_length=255)),
                ('participant_id', models.CharField(max_length=255)),
                ('bot_owner_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('bot_owner_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('bot_owner_mob_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_mob_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bot_and_user_mapping',
                'unique_together': {('tenant_id', 'bot_id', 'participant_id')},
            },
        ),
    ]
