# Generated by Django 4.1.7 on 2024-01-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_coachcoacheementormenteeprofile_mob_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcoacheementormenteeprofile',
            name='profile_type',
            field=models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee'), ('coach-mentor', 'coach mentor'), ('skill_bot', 'skill bot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='signaturebot',
            name='bot_type',
            field=models.CharField(blank=True, choices=[('avatar_bot', 'avatar bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot')], max_length=255, null=True),
        ),
    ]
