# Generated by Django 4.1.7 on 2024-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_coachcoacheementormenteeprofile_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattribute',
            name='competency_data',
            field=models.JSONField(blank=True, default={'1': 'Communication Skills', '2': 'Teamwork', '3': 'Planning and Organizing', '4': 'Client Focus'}, null=True),
        ),
    ]
