# Generated by Django 4.1.7 on 2024-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_userattribute_competency_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member'), ('client_admin', 'client admin'), ('super_admin', 'super admin')], max_length=255),
        ),
    ]
