# Generated by Django 4.1.7 on 2024-02-05 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCoacheeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('coach_id', models.CharField(max_length=64)),
                ('coachee_id', models.CharField(max_length=64)),
                ('mentor_id', models.CharField(max_length=64)),
                ('mentee_id', models.CharField(max_length=64)),
                ('connection_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('blocked', 'blocked'), ('removed', 'removed')], default='pending', max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('is_rejected', models.BooleanField(default=False, null=True)),
                ('is_blocked', models.BooleanField(default=False, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('is_removed', models.BooleanField(default=False, null=True)),
                ('coach_avatar_bot_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'coach_coachee_connection',
                'unique_together': {('tenant_id', 'mentor_id', 'mentee_id'), ('tenant_id', 'coach_id', 'coachee_id')},
            },
        ),
    ]
