# Generated by Django 4.1.7 on 2024-02-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_coachcoacheeconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcoacheeconnection',
            name='coach_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coachcoacheeconnection',
            name='coachee_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coachcoacheeconnection',
            name='mentee_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coachcoacheeconnection',
            name='mentor_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
