# Generated by Django 4.1.7 on 2024-02-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_coachcoacheeconnection_coach_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='use_personality_context',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
