# Generated by Django 4.1.7 on 2024-02-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_signaturebot_use_personality_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='use_idp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
