# Generated by Django 4.1.7 on 2024-02-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_signaturebot_use_idp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='accessed_bot_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='coach_expertise',
            field=models.TextField(blank=True, default='Career Management,Work Life Banlance,Project Management,Lateral Transfers', null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='coach_skills',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='departments',
            field=models.TextField(blank=True, default='Sales & Marketing,Production,Design,Engineering,HR & Training', null=True),
        ),
    ]
