# Generated by Django 4.1.7 on 2024-02-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_clientuserinfo_accessed_bot_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='allow_coachee_to_create_session',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
