# Generated by Django 4.1.7 on 2024-02-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_coachcoacheementormenteeprofile_allow_coachee_to_create_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='is_mentor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='qna_for_coach_mentor',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
