# Generated by Django 4.1.7 on 2024-02-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_coachcoacheementormenteeprofile_is_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='coach_menor_previledge',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
