# Generated by Django 4.1.7 on 2024-02-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_clientuserinfo_coach_menor_previledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientuserinfo',
            old_name='coach_menor_previledge',
            new_name='coach_mentor_previledge',
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='is_coach_mentor_previledge',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
