# Generated by Django 4.1.7 on 2024-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_coach_menor_previledge_clientuserinfo_coach_mentor_previledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='common_phrases_and_expressions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='significant_challenges_and_solutions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='signaturebot',
            name='bot_type',
            field=models.CharField(blank=True, choices=[('avatar_bot', 'avatar bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot')], max_length=255, null=True),
        ),
    ]
