# Generated by Django 4.1.7 on 2024-03-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_coachcoacheementormenteeprofile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='botattribute',
            name='about',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='signaturebot',
            name='bot_scenario_case',
            field=models.CharField(blank=True, choices=[('role_bot', 'role bot'), ('skill_bot', 'skill bot'), ('general', 'general')], default='general', max_length=255, null=True),
        ),
    ]
