# Generated by Django 4.1.7 on 2024-03-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_botattribute_about_signaturebot_bot_scenario_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='botattribute',
            name='admirer_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
