# Generated by Django 4.1.7 on 2024-03-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_coachcoacheementormenteeprofile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='admirer_user_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
