# Generated by Django 4.1.7 on 2024-03-13 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_coachcoacheementormenteeprofile_admirer_user_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCoacheeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('coach_id', models.CharField(max_length=255)),
                ('coachee_id', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('rating_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('rating_comment', models.TextField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'coach_coachee_rating',
                'unique_together': {('tenant_id', 'coach_id', 'coachee_id', 'is_deleted')},
            },
        ),
    ]
