# Generated by Django 4.1.7 on 2024-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_coachcoacheerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcoacheerating',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
