# Generated by Django 4.1.7 on 2024-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_coachcoacheementormenteeprofile_profile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='restricted_features',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='restricted_pages',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
