# Generated by Django 4.1.7 on 2024-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_clientuserinfo_restricted_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botattribute',
            name='ui_information',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='coachcoacheementormenteeprofile',
            name='profile_type',
            field=models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee'), ('coach-mentor', 'coach mentor'), ('skill_bot', 'skill bot'), ('coachbots', 'coachbots'), ('external', 'external'), ('icons_by_ai', 'icons by ai'), ('knowledge_bot', 'knowledge bot'), ('customer_avatar', 'customer avatar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='signaturebot',
            name='bot_scenario_case',
            field=models.CharField(blank=True, choices=[('role_bot', 'role bot'), ('skill_bot', 'skill bot'), ('skill_guide', 'skill guide'), ('general', 'general'), ('icons_by_ai', 'icons by ai'), ('customer_avatar', 'customer avatar')], default='general', max_length=255, null=True),
        ),
    ]
