# Generated by Django 4.1.7 on 2024-03-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_botattribute_ui_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaturebot',
            name='prompt',
        ),
    ]
