# Generated by Django 4.1.7 on 2024-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_remove_signaturebot_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='botattribute',
            name='extracted_documents',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
