# Generated by Django 4.1.7 on 2024-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_botattribute_extracted_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='journey_and_background',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
