# Generated by Django 4.1.7 on 2024-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_coachcoacheementormenteeprofile_journey_and_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='mentorship_contribution',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
