# Generated by Django 4.1.7 on 2024-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_coachcoacheementormenteeprofile_mentorship_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='is_approved_email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
