# Generated by Django 4.1.7 on 2024-04-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_coachcoacheementormenteeprofile_is_approved_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='is_approval_email_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
