# Generated by Django 4.1.7 on 2024-04-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_signaturebot_is_approval_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='evaluate_relevency',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
