# Generated by Django 4.1.7 on 2024-05-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_userattribute_evaluate_relevency'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='domain_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='owner_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
