# Generated by Django 4.1.7 on 2024-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_clientuserinfo_domain_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='deepdive_accessed_emails',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='coachcoacheementormenteeprofile',
            name='profile_type',
            field=models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee'), ('coach-mentor', 'coach mentor'), ('skill_bot', 'skill bot'), ('coachbots', 'coachbots'), ('external', 'external'), ('icons_by_ai', 'icons by ai'), ('knowledge_bot', 'knowledge bot'), ('customer_avatar', 'customer avatar'), ('deep_dive', 'deep dive')], max_length=255),
        ),
        migrations.AlterField(
            model_name='signaturebot',
            name='bot_type',
            field=models.CharField(blank=True, choices=[('avatar_bot', 'avatar bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], max_length=255, null=True),
        ),
    ]
