# Generated by Django 4.1.7 on 2024-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_clientuserinfo_deepdive_accessed_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='allowed_ips',
            field=models.JSONField(blank=True, default={'feedback_deep-dive': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member'), ('client_admin', 'client admin'), ('deep_dive_creator', 'super admin')], max_length=255),
        ),
    ]
