# Generated by Django 4.1.7 on 2024-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_clientuserinfo_allowed_ips_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='discussion_topic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='signaturebot',
            name='access_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signaturebot',
            name='bot_expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='coach_expertise',
            field=models.TextField(blank=True, default='Leadership Development,Stress Management,Hiring & Recruitment,People Management,Diversity & Inclusion,Career Navigation,Culture Alignment,Workplace Skills', null=True),
        ),
    ]
