# Generated by Django 4.1.7 on 2024-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_coachcoacheementormenteeprofile_discussion_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='allow_audio_interactions',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='allow_audio_interactions',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member'), ('client_admin', 'client admin'), ('super_admin', 'super admin'), ('deep_dive_creator', 'deep dive creator')], max_length=255),
        ),
    ]
