# Generated by Django 4.1.7 on 2024-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_clientuserinfo_allow_audio_interactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='make_new_user_in_trail',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
