# Generated by Django 4.1.7 on 2024-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_clientuserinfo_make_new_user_in_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='prioritize_user_audio_interaction',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
