# Generated by Django 4.1.7 on 2024-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_userattribute_prioritize_user_audio_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='restricted_features',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='restricted_pages',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
