# Generated by Django 4.1.7 on 2024-05-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_userattribute_restricted_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='assigned_tests',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
