# Generated by Django 4.1.7 on 2024-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_userattribute_assigned_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allow_audio_interactions',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='is_coach_mentor_previledge',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='make_new_user_in_trail',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
