# Generated by Django 4.1.7 on 2024-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_userattribute_assigned_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='access_allowed',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='access_denied',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
