# Generated by Django 4.1.7 on 2024-05-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_userattribute_access_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
