# Generated by Django 4.1.7 on 2024-05-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_alter_clientuserinfo_allow_audio_interactions_and_more'),
        ('users', '0068_userattribute_preferences'),
    ]

    operations = [
    ]
