# Generated by Django 4.1.7 on 2024-05-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_merge_20240531_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='heading',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='sub_heading',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='tag_line',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
