# Generated by Django 4.1.7 on 2024-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_clientuserinfo_heading_clientuserinfo_sub_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='optional_file_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
