# Generated by Django 4.1.7 on 2024-06-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_coachcoacheementormenteeprofile_optional_file_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='ui_information',
            field=models.JSONField(blank=True, default={'bottom_text': None, 'header': None, 'read_text': None}, null=True),
        ),
    ]
