# Generated by Django 4.1.7 on 2024-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_clientuserinfo_ui_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='widget_access_code',
            field=models.CharField(blank=True, default='DEMO2024', max_length=255, null=True),
        ),
    ]
