# Generated by Django 4.1.7 on 2024-06-11 08:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_clientuserinfo_widget_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=users.models.get_default_allowed_ips, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='ui_information',
            field=models.JSONField(blank=True, default=users.models.get_default_ui_information, null=True),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='competency_data',
            field=models.JSONField(blank=True, default=users.models.default_competency_data, null=True),
        ),
    ]
