# Generated by Django 4.1.7 on 2024-06-12 09:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_alter_clientuserinfo_allowed_ips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='page_informations',
            field=models.JSONField(blank=True, default=users.models.get_default_signature_bot_page_information, null=True),
        ),
    ]
