# Generated by Django 4.1.7 on 2024-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_signaturebot_page_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='problem_statement',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
