# Generated by Django 4.1.7 on 2024-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_coachcoacheementormenteeprofile_problem_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcoacheementormenteeprofile',
            name='problem_statement',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
