# Generated by Django 4.1.7 on 2024-06-19 06:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_alter_coachcoacheementormenteeprofile_problem_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRecommendationsForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('coach_recommendations', models.TextField(blank=True, default=None, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_recommendations', to='users.coachcoacheementormenteeprofile')),
            ],
            options={
                'db_table': 'coach_recommendations_for_user',
            },
        ),
        migrations.AddIndex(
            model_name='coachrecommendationsforuser',
            index=models.Index(fields=['user_profile'], name='coach_recom_user_pr_a0746f_idx'),
        ),
        migrations.AddIndex(
            model_name='coachrecommendationsforuser',
            index=models.Index(fields=['tenant_id', 'user_profile'], name='coach_recom_tenant__91c058_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coachrecommendationsforuser',
            unique_together={('tenant_id', 'user_profile')},
        ),
    ]
