# Generated by Django 4.1.7 on 2024-06-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_coachrecommendationsforuser_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coachrecommendationsforuser',
            unique_together={('tenant_id', 'user_profile', 'deleted')},
        ),
    ]
