# Generated by Django 4.1.7 on 2024-06-19 13:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_alter_coachrecommendationsforuser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='help_text',
            field=models.JSONField(blank=True, default=users.models.get_default_help_text, null=True),
        ),
    ]
