# Generated by Django 4.1.7 on 2024-06-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_clientuserinfo_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='allow_paste_answer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
