# Generated by Django 4.1.7 on 2024-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_clientuserinfo_allow_paste_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allow_paste_answer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
