# Generated by Django 4.1.7 on 2024-06-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_alter_clientuserinfo_allow_paste_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='webhook_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='webhook_secret',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='webhook_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='webhook_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
