# Generated by Django 4.1.7 on 2024-06-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_clientuserinfo_webhook_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='provide_answers_using_emojis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
