# Generated by Django 4.1.7 on 2024-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_coachcoacheementormenteeprofile_provide_answers_using_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='excluded_users',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
