# Generated by Django 4.1.7 on 2024-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_clientuserinfo_excluded_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='use_skills_from_skill_bank',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
