# Generated by Django 4.1.7 on 2024-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_clientuserinfo_use_skills_from_skill_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='is_private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
