# Generated by Django 4.1.7 on 2024-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_signaturebot_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='send_profile_for_reapproval',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='use_skills_from_skill_bank',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
