# Generated by Django 4.1.7 on 2024-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_clientuserinfo_send_profile_for_reapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='email_address_list',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
