# Generated by Django 4.1.7 on 2024-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_clientuserinfo_email_address_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allow_audio_interactions',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
