# Generated by Django 4.1.7 on 2024-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_alter_clientuserinfo_allow_audio_interactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='additional_coachee_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
