# Generated by Django 4.1.7 on 2024-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_coachcoacheementormenteeprofile_additional_coachee_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='use_coachee_info_in_prompt',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
