# Generated by Django 4.1.7 on 2024-08-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_coachcoacheementormenteeprofile_use_coachee_info_in_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='system_instructions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
