# Generated by Django 4.1.7 on 2024-08-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_signaturebot_system_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='allow_public_access',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
