# Generated by Django 4.1.7 on 2024-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_signaturebot_allow_public_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='integratable_widget_snippet',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
