# Generated by Django 4.1.7 on 2024-08-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_signaturebot_integratable_widget_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturebot',
            name='integratable_widget_snippet',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
