# Generated by Django 4.1.7 on 2024-09-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_alter_signaturebot_integratable_widget_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcoacheementormenteeprofile',
            name='meeting_availability',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
