# Generated by Django 4.1.7 on 2024-10-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_coachcoacheementormenteeprofile_meeting_availability'),
        ('users', '0097_reportconfig'),
    ]

    operations = [
    ]
