# Generated by Django 4.1.7 on 2024-10-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_merge_20241007_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturebot',
            name='bot_type',
            field=models.CharField(blank=True, choices=[('avatar_bot', 'avatar bot'), ('subject_specific_bot', 'subject specific bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], max_length=255, null=True),
        ),
    ]
