# Generated by Django 4.1.7 on 2024-11-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_alter_signaturebot_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='allow_access_to_platform',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='allow_access_to_snippet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='report_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='widget_access_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
