# Generated by Django 4.1.7 on 2024-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_clientuserinfo_allow_access_to_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfig',
            name='psychometric_culture_explanation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='psychometric_culture_rating',
            field=models.BooleanField(default=True),
        ),
    ]
