# Generated by Django 4.1.7 on 2024-12-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_reportconfig_psychometric_culture_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='report_on',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
