# Generated by Django 4.1.7 on 2025-01-17 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_alter_botandusermapping_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('access_code', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_access_code', to='users.clientuserinfo')),
            ],
            options={
                'db_table': 'access_code',
                'unique_together': {('deleted', 'client', 'access_code')},
            },
        ),
        migrations.CreateModel(
            name='AccessCodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('session_attempted', models.IntegerField(blank=True, default=0, null=True)),
                ('max_test_attempts', models.IntegerField(blank=True, default=2, null=True)),
                ('access_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.snippetaccesscode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='users.user')),
            ],
            options={
                'db_table': 'access_code_log',
                'unique_together': {('deleted', 'access_code', 'user')},
            },
        ),
    ]
