# Generated by Django 4.1.7 on 2025-01-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_snippetaccesscode_accesscodelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscodelog',
            name='max_test_attempts',
        ),
        migrations.AddField(
            model_name='snippetaccesscode',
            name='max_test_attempts',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
