# Generated by Django 4.1.7 on 2025-02-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_remove_accesscodelog_max_test_attempts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscodelog',
            options={'verbose_name': 'Snippet Access Code Log', 'verbose_name_plural': 'Snippet Access Code Logs'},
        ),
        migrations.AlterModelOptions(
            name='botattribute',
            options={'verbose_name': 'Signature Bot Attribute', 'verbose_name_plural': 'Signature Bot Attributes'},
        ),
    ]
