# Generated by Django 4.1.7 on 2025-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0106_alter_accesscodelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='show_recommendations',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
