# Generated by Django 4.1.7 on 2025-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_clientuserinfo_show_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='show_recommendations',
            field=models.BooleanField(default=True),
        ),
    ]
