# Generated by Django 4.1.7 on 2025-04-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_alter_clientuserinfo_show_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='use_latest_simualation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
