# Generated by Django 4.1.7 on 2025-04-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_clientuserinfo_ask_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_repeat',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
