# Generated by Django 4.1.7 on 2025-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0111_user_is_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='is_repeat',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
