# Generated by Django 4.1.7 on 2025-04-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_clientuserinfo_is_repeat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportconfig',
            options={'verbose_name': 'Client Report Config', 'verbose_name_plural': 'Client Report Configs'},
        ),
        migrations.AlterUniqueTogether(
            name='reportconfig',
            unique_together={('deleted', 'client')},
        ),
    ]
