# Generated by Django 4.1.7 on 2025-05-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_alter_reportconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='test_per_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='test_per_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
