# Generated by Django 4.1.7 on 2025-05-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0114_clientuserinfo_test_per_month_user_test_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='test_per_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_per_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
