# Generated by Django 4.1.7 on 2025-08-13 05:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_alter_clientuserinfo_test_per_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturebot',
            name='bot_scenario_case',
            field=models.CharField(blank=True, choices=[('role_bot', 'role bot'), ('skill_bot', 'skill bot'), ('skill_guide', 'skill guide'), ('general', 'general'), ('icons_by_ai', 'icons by ai'), ('customer_avatar', 'customer avatar'), ('ai_agent', 'ai agent')], default='general', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserMindmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('mindmap_links', models.TextField(help_text='Enter links separated by commas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
