# Generated by Django 4.1.7 on 2025-08-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0116_alter_signaturebot_bot_scenario_case_usermindmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturebot',
            name='email_address_list',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='signaturebot',
            name='send_bot_transcript',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
