# Generated by Django 4.1.7 on 2025-08-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_signaturebot_email_address_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturebot',
            name='send_bot_transcript',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
