# Generated by Django 4.1.7 on 2025-09-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_alter_signaturebot_send_bot_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='button_controls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='report_on',
            field=models.BooleanField(blank=True, help_text='to enable or disable reporting for the test.', null=True),
        ),
    ]
