# Generated by Django 4.1.7 on 2025-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_clientuserinfo_button_controls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='button_controls',
            field=models.JSONField(blank=True, default=dict, help_text='for eg: {"mode_button": {"show": true}, "mindmap_button": {"show": true}, "assessment_button": {"show": true}}'),
        ),
    ]
