# Generated by Django 4.1.7 on 2025-10-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_alter_clientuserinfo_button_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='leaderboard_report_password',
            field=models.CharField(default='demobook#12345', max_length=25),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='leaderboard_report_protected',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
