# Generated by Django 4.1.7 on 2025-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0168_merge_20251008_1045'),
        ('users', '0121_clientuserinfo_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, related_name='client_users', to='tests.test'),
        ),
    ]
