# Generated by Django 4.1.7 on 2025-10-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_conversations', '0004_botresponseprompt'),
        ('users', '0122_clientuserinfo_assigned_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='assigned_bots',
            field=models.ManyToManyField(blank=True, related_name='client_users', to='coaching_conversations.botresponseprompt'),
        ),
    ]
