# Generated by Django 4.1.7 on 2025-10-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0123_clientuserinfo_assigned_bots'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='bot_config',
            field=models.JSONField(blank=True, default=dict, help_text='for eg: {"coaching": {"show":true,  "botid": "xyz"},"simulation": {"show":true}}'),
        ),
    ]
