# Generated by Django 4.1.7 on 2025-11-03 07:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_clientuserinfo_bot_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='coaching_credits_per_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='LibraryBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('bot_config', models.JSONField(blank=True, default=dict, help_text='for eg: {"coaching": {"show":true,  "botid": "xyz"},"simulation": {"show":true}}')),
                ('show_certification_badge', models.BooleanField(blank=True, default=True, help_text='To show certification batch in library bot config')),
                ('default_filters', models.TextField(blank=True, default=None, help_text="Default filters for library bot config, (comma sep) e.g:'leadership, communication, emerging_player' if emerging_player is latest=true, else latest=false", null=True)),
                ('leaderboard_report_protected', models.BooleanField(blank=True, default=True)),
                ('leaderboard_report_password', models.CharField(default='demobook#12345', max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_bot_config', to='users.clientuserinfo')),
            ],
            options={
                'db_table': 'library_bot_config',
                'unique_together': {('deleted', 'client')},
            },
        ),
    ]
