# Generated by Django 4.1.7 on 2025-11-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_clientuserinfo_coaching_credits_per_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='librarybotconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='library_bot_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.librarybotconfig'),
        ),
        migrations.RemoveField(
            model_name='librarybotconfig',
            name='client',
        ),
    ]
