# Generated by Django 4.1.7 on 2025-11-04 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_alter_librarybotconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuserinfo',
            name='library_bot_config',
        ),
        migrations.AddField(
            model_name='librarybotconfig',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='library_bot_config', to='users.clientuserinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='bot_config',
            field=models.JSONField(blank=True, default=dict, help_text='for eg: {"coaching": {"show":true,  "bot_id": "xyz"},"simulation": {"show":true}}'),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='bot_config',
            field=models.JSONField(blank=True, default=dict, help_text='for eg: {"coaching": {"show":true,  "bot_id": "xyz"},"simulation": {"show":true}}'),
        ),
    ]
