# Generated by Django 4.1.7 on 2025-11-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_remove_clientuserinfo_library_bot_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybotconfig',
            name='default_filters',
            field=models.JSONField(blank=True, default=None, help_text="Default filters for the library bot, e.g., {'industry': 'communication', 'business_outcome': 'beginner'}", null=True),
        ),
    ]
