# Generated by Django 4.1.7 on 2025-11-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_alter_librarybotconfig_default_filters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientuserinfo',
            old_name='bot_config',
            new_name='universal_bot_config',
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='default_filters',
            field=models.JSONField(blank=True, default={'business_outcome': '', 'emerging_players': '', 'function': '', 'implementation_complexity': '', 'industry': '', 'unexpected_outcomes': ''}, help_text='Default filters for the library bot, e.g., {"function": "", "industry": "Banking", "business_outcome": "", "emerging_players": "", "unexpected_outcomes": "", "implementation_complexity": ""} emerging_player can be true/false/empty keep empty any field to ignore filter ', null=True),
        ),
    ]
