# Generated by Django 4.1.7 on 2025-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0129_rename_bot_config_clientuserinfo_universal_bot_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conversation_per_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
