# Generated by Django 4.1.7 on 2025-11-06 11:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_user_conversation_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybotconfig',
            name='default_filters',
            field=models.JSONField(blank=True, default=users.models.get_default_library_bot_value, help_text='Default filters for the library bot, e.g., {"function": "", "industry": "Banking", "business_outcome": "", "emerging_players": "", "unexpected_outcomes": "", "implementation_complexity": ""} emerging_player can be true/false/empty keep empty any field to ignore filter ', null=True),
        ),
    ]
