# Generated by Django 4.1.7 on 2025-11-17 05:59

from django.db import migrations, models
import users.choices
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0131_alter_librarybotconfig_default_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybotconfig',
            name='feature_and_button_controls',
            field=models.JSONField(blank=True, default=users.choices.get_default_library_bot_button_controls, help_text='for eg: {"leadership_button": {"label": "Leadership", "show": true}, "idea_board_button": {"label": "IdeaBoard Report", "show": true}, "ai_pulse": {"label": "AI Pulse Report", "show": true}}'),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='default_filters',
            field=models.JSONField(blank=True, default=users.models.get_default_library_bot_value, help_text='Default filters for the library bot, e.g., {"function": "", "industry": "Banking", "business_outcome": "", "emerging_players": "", "startup": "", "unexpected_outcomes": "", "implementation_complexity": ""} emerging_player can be true/false/empty keep empty any field to ignore filter ', null=True),
        ),
    ]
