# Generated by Django 4.1.7 on 2025-11-20 08:30

from django.db import migrations, models
import django.db.models.deletion
import users.choices
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0132_librarybotconfig_feature_and_button_controls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybotconfig',
            name='ai_pulse_report_password',
            field=models.CharField(default='demobook#12345', max_length=25),
        ),
        migrations.AddField(
            model_name='librarybotconfig',
            name='ai_pulse_report_protected',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='librarybotconfig',
            name='ideaboard_report_password',
            field=models.CharField(default='demobook#12345', max_length=25),
        ),
        migrations.AddField(
            model_name='librarybotconfig',
            name='ideaboard_report_protected',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name='PortalPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('bot_config', models.JSONField(blank=True, default=dict, help_text='for eg: {"coaching": {"show":true,  "bot_id": "xyz"},"simulation": {"show":true}}')),
                ('simulation_report_protected', models.BooleanField(blank=True, default=True)),
                ('simulation_report_password', models.CharField(default='demosimulation#12345', max_length=25)),
                ('feature_and_button_controls', models.JSONField(blank=True, default=users.choices.get_default_portal_page_config, help_text='for eg: {"sim_report": {"label": "Report", "show": true}}')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_page_config', to='users.clientuserinfo')),
            ],
            options={
                'db_table': 'portal_page_config',
            },
        ),
    ]
