# Generated by Django 4.1.7 on 2025-11-26 12:15

from django.db import migrations, models
import users.choices


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0134_alter_librarybotconfig_feature_and_button_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybotconfig',
            name='feature_and_button_controls',
            field=models.JSONField(blank=True, default=users.choices.get_default_library_bot_button_controls, help_text='for eg: {"leadership_button": {"label": "Leadership", "show": true}, "idea_board_button": {"label": "IdeaBoard Report", "show": true}, "ai_pulse": {"label": "AI Pulse Report", "show": true}, "transform_iq_feature": {"label": "Transform IQ", "show": true}, "metadata_filters": {"label": "", "show": true}}'),
        ),
    ]
