# Generated by Django 4.1.7 on 2025-11-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0183_remove_collection_client'),
        ('users', '0135_alter_librarybotconfig_feature_and_button_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='client_users', to='tests.collection'),
        ),
    ]
