# Generated by Django 4.1.7 on 2025-12-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0136_clientuserinfo_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='show_recommendations',
            field=models.BooleanField(default=False, help_text='to switch on/off the simualation recommandation after attempting a simulation/interction.'),
        ),
    ]
