# Generated by Django 4.1.7 on 2025-12-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0137_alter_clientuserinfo_show_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybotconfig',
            name='login_view',
            field=models.CharField(blank=True, choices=[('no_login', 'No Login'), ('email_password', 'Email + Password'), ('email_only', 'Only Email')], default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='portalpageconfig',
            name='login_view',
            field=models.CharField(blank=True, choices=[('no_login', 'No Login'), ('email_password', 'Email + Password'), ('email_only', 'Only Email')], default=None, max_length=55, null=True),
        ),
    ]
