# Generated by Django 4.1.7 on 2025-12-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0138_librarybotconfig_login_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='session_context',
            field=models.BooleanField(default=False, help_text='Used to on/off context asking before any interaction'),
        ),
    ]
