# Generated by Django 4.1.7 on 2026-01-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0139_clientuserinfo_session_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybotconfig',
            name='login_dashboard',
            field=models.CharField(blank=True, choices=[('client_only_setup', 'Only Client Setup'), ('user_specific_setup', 'User Specific Setup')], default='client_only_setup', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='portalpageconfig',
            name='login_dashboard',
            field=models.CharField(blank=True, choices=[('client_only_setup', 'Only Client Setup'), ('user_specific_setup', 'User Specific Setup')], default='client_only_setup', max_length=55, null=True),
        ),
    ]
