# Generated by Django 4.1.7 on 2026-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_librarybotconfig_login_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='client_logo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='librarybotconfig',
            name='announcements_section',
            field=models.JSONField(blank=True, default=None, help_text='\n{\n  enabled: boolean;\n  heading: {\n    text: string;\n    link: string | null;\n    link_text: string | null;\n    append_text?: string;\n  },\n  subheading: {\n    text: string;\n    link: string | null;\n    link_text: string | null;\n    append_text?: string;\n\n  }\n}\n', null=True),
        ),
        migrations.AddField(
            model_name='librarybotconfig',
            name='card_button_label',
            field=models.JSONField(blank=True, default=None, help_text='for eg: {"description": "TransformIQ", "report": "Report"}', null=True),
        ),
        migrations.AddField(
            model_name='librarybotconfig',
            name='feature_boxs',
            field=models.JSONField(blank=True, default=None, help_text='for eg: ["xyz feature", "abc feature"]', null=True),
        ),
    ]
