# Generated by Django 4.1.7 on 2026-01-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0141_clientuserinfo_client_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarybotconfig',
            name='card_button_label',
        ),
        migrations.AddField(
            model_name='librarybotconfig',
            name='card_button_config',
            field=models.JSONField(blank=True, default=None, help_text='for eg: {"description": {"show": true, "label": "TransformIQ"}, "report": {"show": true, "label": "TransformIQ"}, "audio_button": {"show": true, "label": ""}}', null=True),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='announcements_section',
            field=models.JSONField(blank=True, default=None, help_text='\n        {\n        enabled: boolean;\n        heading: {\n            text: string;\n            link: string | null;\n            link_text: string | null;\n            append_text?: string;\n        },\n        subheading: {\n            text: string;\n            link: string | null;\n            link_text: string | null;\n            append_text?: string;\n\n        }\n        }\n        ', null=True),
        ),
    ]
