# Generated by Django 4.1.7 on 2026-02-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0142_remove_librarybotconfig_card_button_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybotconfig',
            name='access_password',
            field=models.CharField(default='Client@2026', max_length=25),
        ),
        migrations.AddField(
            model_name='portalpageconfig',
            name='access_password',
            field=models.CharField(default='Client@2026', max_length=25),
        ),
    ]
