# Generated by Django 4.1.7 on 2026-02-23 04:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0143_librarybotconfig_access_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.CharField(max_length=125)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='users.clientuserinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
