# Generated by Django 4.1.7 on 2026-02-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0144_clientresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientresource',
            name='client',
        ),
        migrations.AddField(
            model_name='clientuserinfo',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='client_users', to='users.clientresource'),
        ),
    ]
