# Generated by Django 4.1.7 on 2026-02-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0145_remove_clientresource_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientresource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
    ]
