# Generated by Django 4.1.7 on 2026-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0146_alter_clientresource_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientresource',
            name='label',
            field=models.CharField(default=None, max_length=125),
            preserve_default=False,
        ),
    ]
