# Generated by Django 4.1.7 on 2026-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0147_clientresource_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserinfo',
            name='company_information',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
