# Generated by Django 4.1.7 on 2026-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0148_clientuserinfo_company_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientresource',
            name='info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
