# Generated by Django 4.1.7 on 2026-03-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_alter_clientuserinfo_accessed_bot_ids_and_more'),
        ('users', '0149_clientresource_info'),
    ]

    operations = [
    ]
