# Generated by Django 4.1.7 on 2026-04-03 04:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0202_conceptsession_case_module'),
        ('coaching_conversations', '0004_botresponseprompt'),
        ('users', '0149_clientresource_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='accessed_bot_ids',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated bot IDs accessible to all client members.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allow_access_to_platform',
            field=models.BooleanField(default=True, help_text='Deprecated.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allow_access_to_snippet',
            field=models.BooleanField(default=True, help_text='Deprecated.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allow_audio_interactions',
            field=models.BooleanField(blank=True, default=True, help_text='Enable audio playback for bot questions and responses.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allow_paste_answer',
            field=models.BooleanField(blank=True, default=False, help_text='Allow users to paste answers during simulations.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=users.models.get_default_allowed_ips, help_text='IP whitelist. If set, access is allowed only from these IPs.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='ask_access_code',
            field=models.BooleanField(default=True, help_text='Require access code before allowing widget usage.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='assigned_bots',
            field=models.ManyToManyField(blank=True, help_text='Response styles available to this client.', related_name='client_users', to='coaching_conversations.botresponseprompt'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, help_text='Tests assigned to this client.', related_name='client_users', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='attributes',
            field=models.JSONField(blank=True, default=None, help_text='Custom extensible metadata for the client (key-value JSON).', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='avatar_bot_creation',
            field=models.BooleanField(default=False, help_text='If enabled, members can create Avatar Bots.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='button_controls',
            field=models.JSONField(blank=True, default=dict, help_text='Controls widget buttons. Example: {"mode_button": {"show": true}, "mindmap_button": {"show": true}, "assessment_button": {"show": true}}'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='client_logo',
            field=models.CharField(blank=True, default=None, help_text='Client Logo Url', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='client_name',
            field=models.CharField(help_text='Unique client identifier within a tenant (e.g., L&T, Client-Demo).', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='coach_expertise',
            field=models.TextField(blank=True, default='Leadership Development,Stress Management,Hiring & Recruitment,People Management,Diversity & Inclusion,Career Navigation,Culture Alignment,Workplace Skills', help_text='Expertise areas used for directory filtering.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='coach_mentor_previledge',
            field=models.TextField(blank=True, default=None, help_text='Emails allowed to act as coach or mentor.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='coach_skills',
            field=models.TextField(blank=True, default=None, help_text='Skills used for filtering in coach directory.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='coaching_credits_per_month',
            field=models.IntegerField(blank=True, default=0, help_text='Deprecated. Use number_of_conversation_per_month instead.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Library collections accessible to this client.', related_name='client_users', to='tests.collection'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='company_information',
            field=models.JSONField(blank=True, default=None, help_text='Company Related Info like website and all', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='deepdive_accessed_emails',
            field=models.TextField(blank=True, default=None, help_text='Deprecated. Previously used for deep-dive bot access.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='demo_ids',
            field=models.TextField(blank=True, default=None, help_text='Emails treated as demo users (acts similar to restriction).', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='departments',
            field=models.TextField(blank=True, default='Sales & Marketing,Production,Design,Engineering,HR & Training', help_text='Department names used for directory filtering.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='domain_name',
            field=models.CharField(blank=True, default=None, help_text='Comma-separated domains mapped to this client (used for access control).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='email_address_list',
            field=models.TextField(blank=True, default=None, help_text='Emails that receive simulation attempt reports.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='excluded_users',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated emails excluded from reports and analytics.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='feedback_bot_creation',
            field=models.BooleanField(default=False, help_text='If enabled, members can create Feedback Bots.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='heading',
            field=models.CharField(blank=True, default=None, help_text='Main heading shown on directory or widget pages.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='help_text',
            field=models.JSONField(blank=True, default=users.models.get_default_help_text, help_text='Client-specific help or informational text.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Enable or disable this client across the entire platform.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='is_coach_mentor_previledge',
            field=models.BooleanField(blank=True, default=False, help_text='Enable coach/mentor privilege enforcement.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='is_repeat',
            field=models.BooleanField(blank=True, default=None, help_text='Allow repeat test attempts. Overrides tenant-level setting.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='leaderboard_report_password',
            field=models.CharField(default='demobook#12345', help_text='Password used to access leaderboard reports.', max_length=25, verbose_name='Universal Page Password'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='leaderboard_report_protected',
            field=models.BooleanField(blank=True, default=True, help_text='Password-protect we are using it as universal page setting if not specified in library bot and portal page. ', verbose_name='Universal Page protected'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='make_new_user_in_trail',
            field=models.BooleanField(blank=True, default=True, help_text='Place newly created users into trial mode. meaning (a demo user)'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='member_emails',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated list of emails belonging to this client.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='member_mob_numbers',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated list of mobile numbers (currently unused).', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='member_user_ids',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated internal user IDs (currently unused).', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='number_of_conversation_per_month',
            field=models.IntegerField(blank=True, default=None, help_text='Monthly conversation limit for this client (client-wide).', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='owner_id',
            field=models.CharField(blank=True, default=None, help_text='Owner email or user ID. Used for auto-login in Library Bot.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='report_on',
            field=models.BooleanField(blank=True, help_text='Enable or disable reports (email + UI) after test attempts.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='required_form_fields',
            field=models.JSONField(blank=True, default=None, help_text='Form configuration for bot creation (currently unused).', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='Resources For a client.', related_name='client_users', to='users.clientresource'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='restricted_features',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated list of disabled features.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='restricted_ids',
            field=models.TextField(blank=True, default=None, help_text='Emails explicitly restricted from using the platform.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='restricted_pages',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated list of restricted UI pages.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='send_profile_for_reapproval',
            field=models.BooleanField(blank=True, default=False, help_text='Require re-approval after profile updates.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='session_context',
            field=models.BooleanField(default=False, help_text='Ask users for context before starting any interaction.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='show_recommendations',
            field=models.BooleanField(default=False, help_text='Show AI recommendations after simulation completion.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='sub_heading',
            field=models.CharField(blank=True, default=None, help_text='Subheading shown below the main heading.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='subject_matter_bot_creation',
            field=models.BooleanField(default=False, help_text='Allows Subject Matter Bot creation (currently unused).', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='tag_line',
            field=models.CharField(blank=True, default=None, help_text='Tagline text shown in UI.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='test_per_month',
            field=models.IntegerField(blank=True, default=None, help_text='Monthly test attempt cap for this client.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='ui_information',
            field=models.JSONField(blank=True, default=users.models.get_default_ui_information, help_text='UI configuration for headers, footers, and layout.', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='universal_bot_config',
            field=models.JSONField(blank=True, default=dict, help_text='Controls bot visibility. for eg: {"coaching": {"show":true,  "bot_id": "xyz"},"simulation": {"show":true}}'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='use_skills_from_skill_bank',
            field=models.BooleanField(blank=True, default=False, help_text='Restrict skill uploads to centralized skill bank.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='webhook_enabled',
            field=models.BooleanField(blank=True, default=False, help_text='Enable or disable webhook delivery.'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='webhook_secret',
            field=models.CharField(blank=True, default=None, help_text='Secret used to validate webhook requests.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='webhook_token',
            field=models.CharField(blank=True, default=None, help_text='Authorization token sent with webhook payloads.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='webhook_url',
            field=models.CharField(blank=True, default=None, help_text='Webhook endpoint for pushing test and interaction data.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='widget_access_code',
            field=models.CharField(blank=True, default=None, help_text='Auto-generated access code required for widgets.', max_length=255, null=True),
        ),
    ]
