# Generated by Django 4.1.7 on 2026-04-03 04:51

from django.db import migrations, models
import users.choices


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0150_alter_clientuserinfo_accessed_bot_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='accessed_bot_ids',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated bot IDs accessible to all client members. (mainly icons-by-ai)', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='excluded_users',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated emails excluded from reports and analytics. (currently using only in slack env)', null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='owner_id',
            field=models.EmailField(default='jai@example.com', help_text='Owner email Used for auto-login in Library Bot.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='access_password',
            field=models.CharField(default='Client@2026', help_text='Access password for library bot page, Its part of login system if login view is email + password then for new user they can login with this password ', max_length=25),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='ai_pulse_report_password',
            field=models.CharField(default='demobook#12345', help_text='Password for ai pulse report in library bot, if not specified it will take universal page password setting from client user info model.', max_length=25),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='ai_pulse_report_protected',
            field=models.BooleanField(blank=True, default=True, help_text='Password protect ai pulse report in library bot, if not specified it will take universal page setting from client user info model.'),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='announcements_section',
            field=models.JSONField(blank=True, default=None, help_text='\n        {\n        enabled: boolean;\n        heading: {\n            text: string;\n            link: string | null;\n            link_text: string | null;\n            append_text?: string;\n        },\n        subheading: {\n            text: string;\n            link: string | null;\n            link_text: string | null;\n            append_text?: string;\n\n        }\n        }\n\n        it will show anouncement section in library bot page right under Hero section, if enabled is true and it will have heading and subheading as specified in the json, link and link_text are optional if link is provided then it will make the heading or subheading clickable with the provided link and link_text will be the text which will be shown for the link and append_text is also optional which will be shown after the link text if provided.\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='bot_config',
            field=models.JSONField(blank=True, default=dict, help_text='It controls the bot widget shown in library bot. for eg: {"coaching": {"show":true,  "bot_id": "xyz"},"simulation": {"show":true}}'),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='card_button_config',
            field=models.JSONField(blank=True, default=None, help_text='It controls the buttons which are shown in the card view of library bot and their lable.",', null=True),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='feature_and_button_controls',
            field=models.JSONField(blank=True, default=users.choices.get_default_library_bot_button_controls, help_text='It controls the features and buttons which are shown in library bot for eg: {"leadership_button": {"label": "Leadership", "show": true}, "idea_board_button": {"label": "IdeaBoard Report", "show": true}, "ai_pulse": {"label": "AI Pulse Report", "show": true}, "transform_iq_feature": {"label": "Transform IQ", "show": true}, "metadata_filters": {"label": "", "show": true}}'),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='feature_boxs',
            field=models.JSONField(blank=True, default=None, help_text='for eg: ["xyz feature", "abc feature"] it will show these feature box in library bot page Hero section', null=True),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='ideaboard_report_password',
            field=models.CharField(default='demobook#12345', help_text='Password for idea board report in library bot, if not specified it will take universal page password setting from client user info model.', max_length=25),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='ideaboard_report_protected',
            field=models.BooleanField(blank=True, default=True, help_text='Password protect idea board report in library bot, if not specified it will take universal page setting from client user info model.'),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='leaderboard_report_password',
            field=models.CharField(default='demobook#12345', help_text='Password for leaderboard report in library bot, if not specified it will take universal page password setting from client user info model.', max_length=25),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='leaderboard_report_protected',
            field=models.BooleanField(blank=True, default=True, help_text='Password protect leaderboard report in library bot, if not specified it will take universal page setting from client user info model.'),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='login_dashboard',
            field=models.CharField(blank=True, choices=[('client_only_setup', 'Only Client Setup'), ('user_specific_setup', 'User Specific Setup')], default='client_only_setup', help_text='Login dashboard view for library bot, if not specified client only setup will be default which means after login user will see the same dashboard based on client user info model settings but if user specific setup is selected then after login user will see the dashboard based on their own user attribute settings if exist otherwise it will fallback to client user info model settings.', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='librarybotconfig',
            name='login_view',
            field=models.CharField(blank=True, choices=[('no_login', 'No Login'), ('email_password', 'Email + Password'), ('email_only', 'Only Email')], default='email_password', help_text='Login view for library bot, if not specified email + password will be default login view for library bot.', max_length=55, null=True),
        ),
    ]
