# Generated by Django 4.1.7 on 2026-03-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0150_merge_20260318_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserinfo',
            name='leaderboard_report_password',
            field=models.CharField(default='demobook#12345', help_text='Password used to access leaderboard reports.', max_length=25, verbose_name='Universal Page Password'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='leaderboard_report_protected',
            field=models.BooleanField(blank=True, default=True, help_text='Password-protect we are using it as universal page setting if not specified in library bot and portal page. ', verbose_name='Universal Page protected'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='make_new_user_in_trail',
            field=models.BooleanField(blank=True, default=True, help_text='Place newly created users into trial mode. meaning (a demo user)'),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='universal_bot_config',
            field=models.JSONField(blank=True, default=dict, help_text='Controls bot visibility. for eg: {"coaching": {"show":true,  "bot_id": "xyz"},"simulation": {"show":true}}'),
        ),
    ]
