# Generated by Django 4.1.7 on 2026-04-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0151_alter_clientuserinfo_accessed_bot_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_code',
            field=models.CharField(blank=True, help_text='to reset pw', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientuserinfo',
            name='owner_id',
            field=models.EmailField(help_text='Owner email Used for auto-login in Library Bot. It should be present in member_emails field as well.', max_length=255),
        ),
    ]
