from commons.anthropic import anthropic_completion
from commons.timeit import timeit


@timeit
def get_summary(transcript, choice = "short"):
    """
    Generate a summary of a given transcript using the Anthropic API.

    This function takes a transcript and a choice of summary length as inputs, and returns a summary of the transcript. 
    The summary is generated by the Anthropic API, which uses AI to generate human-like text based on the provided prompt.

    The function constructs a prompt based on the input transcript and the choice of summary length. 
    The prompt is then passed to the `anthropic_completion` function, which sends it to the Anthropic API and returns the generated summary.

    Args:
        transcript (str): The transcript for which a summary is requested.
        choice (str, optional): The choice of summary length. Can be either "short" or "long". Defaults to "short".

    Returns:
        str: The generated summary of the transcript. The summary is stripped of any leading or trailing whitespace.

    Example:
        >>> transcript = "This is a test transcript."
        >>> print(get_summary(transcript, choice="short"))
        "This is a short summary of the test transcript."

    Note:
        The Anthropic API may not always be able to generate a summary that strictly adheres to the constraints specified in the prompt 
        (e.g., the summary may not always be exactly 200 or 500 words long).
    """
    
    short_summary_prompt = f"""
    Transcript : ${transcript}

    Give me a 200-word summary of the given Transcript. Do not leave any details. Give the summary in 5 bullet points. 
    Note: 1) Do not mention the transcript, just give the summary.
    2) The summary should never be less than 200 words.
    3) Do not add any introductory sentences, just give the summary.
    """


    long_summary_prompt = f"""

    Expand Summary -
    Transcript : ${transcript}

    Give me an extra long and very detailed summary of the given Transcript. Do not leave out any details. Do not mention the transcript, just give the summary.
    Note: 1) Do not mention the transcript, just give the summary.
    2) The summary should never be less than 500 words.
    3) Do not add any introductory sentences, just give the summary.
    """

    prompt = short_summary_prompt if choice == "short" else long_summary_prompt
    summary = anthropic_completion(prompt,500)
    summary = summary.split(":")[-1].strip()
    return summary



def get_document_summary(transcript):
    prompt = f"""
    Transcript : ${transcript}

    Give me a 500-word summary of the above transcript. Do not leave out any details. Do not mention the transcript, just give the summary.
    Note: 1) Do not mention the transcript, just give the summary.
     2) Do not add any introductory sentences, just give the summary

    """

    summary = anthropic_completion(prompt,500)
    return summary