# Generated by Django 4.1.7 on 2023-05-23 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_identifier_key', models.CharField(max_length=255)),
                ('entity_identifier_value', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('nbf', models.DateTimeField()),
                ('iat', models.DateTimeField()),
                ('exp', models.DateTimeField()),
                ('v', models.CharField(default=uuid.uuid4, max_length=64)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'custom_auth_refresh_token',
                'unique_together': {('entity_identifier_value', 'entity_identifier_key', 'entity_type')},
            },
        ),
    ]
