# Generated by Django 4.1.7 on 2023-07-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refreshtoken',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='entity_identifier_value',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
