# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0002_alter_refreshtoken_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
