# Generated by Django 4.1.7 on 2025-12-16 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=50)),
                ('hq', models.CharField(max_length=255)),
                ('revenue_us_millions', models.IntegerField()),
                ('employees_full_time', models.IntegerField()),
                ('ai_cloud_leadership_roles', models.JSONField(default=None)),
                ('ai_digital_initiatives', models.JSONField(default=None)),
                ('cloud_tech_stack_signals', models.JSONField(default=None)),
                ('ai_use_cases', models.JSONField(default=None)),
                ('source', models.CharField(choices=[('LLM', 'LLM'), ('CSV', 'CSV')], max_length=10)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CompanyIQ',
                'verbose_name_plural': 'CompanyIQ',
                'ordering': ['-created'],
            },
        ),
    ]
