# Generated by Django 4.1.7 on 2025-12-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_iq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyiq',
            name='company_normalized',
            field=models.CharField(db_index=True, default=None, editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyiq',
            name='transformation_iq_outlook',
            field=models.TextField(blank=True, help_text='12-18 month AI / digital transformation outlook', null=True),
        ),
        migrations.AlterField(
            model_name='companyiq',
            name='ai_cloud_leadership_roles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='companyiq',
            name='ai_digital_initiatives',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='companyiq',
            name='ai_use_cases',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='companyiq',
            name='cloud_tech_stack_signals',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='companyiq',
            name='source',
            field=models.CharField(choices=[('LLM', 'LLM'), ('CSV', 'CSV'), ('Manual', 'Manual')], default='Manual', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='companyiq',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('company_normalized',), name='uniq_active_companyiq'),
        ),
    ]
