# Generated by Django 4.1.7 on 2025-12-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_iq', '0002_companyiq_company_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyiq',
            name='score',
            field=models.JSONField(default=dict, help_text='AI maturity scores and insights'),
        ),
    ]
