# Generated by Django 4.1.7 on 2025-12-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_iq', '0003_companyiq_score'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyiq',
            name='uniq_active_companyiq',
        ),
    ]
