# Generated by Django 4.1.7 on 2026-01-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_iq', '0004_remove_companyiq_uniq_active_companyiq'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyiq',
            name='sticker',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
