# Generated by Django 4.1.7 on 2026-01-20 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0140_librarybotconfig_login_dashboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('view', 'View'), ('submit', 'Submit')], max_length=20)),
                ('feature', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clientuserinfo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'feature'], name='event_event_t_1e65bb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created'], name='event_created_a89c79_idx'),
        ),
    ]
