# Generated by Django 4.1.7 on 2026-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feature_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['feature'], name='event_feature_6e5c36_idx'),
        ),
    ]
