# Generated by Django 4.1.7 on 2026-03-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0147_clientresource_label'),
        ('analytics', '0002_event_feature_path_event_event_feature_6e5c36_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_feature_6e5c36_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='ev_type_feat_idx',
            old_name='event_event_t_1e65bb_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='ev_created_idx',
            old_name='event_created_a89c79_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='users.clientuserinfo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('click', 'Click'), ('read', 'Read')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='feature',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['feature', 'feature_path'], name='ev_feat_path_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['client', 'created'], name='ev_client_created_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'created'], name='ev_user_created_idx'),
        ),
    ]
