# Generated by Django 4.1.7 on 2026-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_event_event_feature_6e5c36_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('click', 'Click'), ('read', 'Read'), ('view', 'View'), ('submit', 'Submit')], db_index=True, max_length=50),
        ),
    ]
