from djchoices import DjangoChoices, ChoiceItem


class TestTypeChoices(DjangoChoices):
    test = ChoiceItem("test")   # feedback at last
    trainer = ChoiceItem("trainer")  # feedback at every question
    # feedback at every question + autogenerated questions
    coaching = ChoiceItem("coaching")
    orchestrated_conversation = ChoiceItem("orchestrated_conversation")
    view = ChoiceItem("view")
    interview = ChoiceItem("interview")
    single = ChoiceItem("single")


class InteractionModeChoices(DjangoChoices):
    text = ChoiceItem("text")
    audio = ChoiceItem("audio")
    video = ChoiceItem("video")


class TestAttemptSessionStatusChoices(DjangoChoices):
    in_progress = ChoiceItem("in_progress")
    completed = ChoiceItem("completed")
    cancelled = ChoiceItem("cancelled")


class QuestionTypeChoices(DjangoChoices):
    subjective = ChoiceItem("subjective")
    objective = ChoiceItem("objective")
    mcq = ChoiceItem("mcq")


class QuestionForChoices(DjangoChoices):
    bot_llm = ChoiceItem("bot_llm")
    user = ChoiceItem("user")


class QuestionResponseTypeChoices(DjangoChoices):
    text = ChoiceItem("text")
    audio = ChoiceItem("audio")
    video = ChoiceItem("video")


class TestQuestionResponseEvaluationStatusChoices(DjangoChoices):
    init = ChoiceItem("init")
    in_progress = ChoiceItem("in_progress")
    success = ChoiceItem("success")
    failed = ChoiceItem("failed")
