from click import Choice
from djchoices import DjangoChoices, ChoiceItem

class PilotTestPreferencesChoices(DjangoChoices):
    only_soft_skills = ChoiceItem("only_soft_skills")
    only_hard_skills = ChoiceItem("only_hard_skills")
    mix = ChoiceItem("mix")

class PilotTestFrequencyChoices(DjangoChoices):
    monday = ChoiceItem("monday")
    mon_and_thu = ChoiceItem("mon_and_thu")


class TestTypeChoices(DjangoChoices):
    test = ChoiceItem("test")   # feedback at last
    trainer = ChoiceItem("trainer")  # feedback at every question
    # feedback at every question + autogenerated questions
    coaching = ChoiceItem("coaching")
    orchestrated_conversation = ChoiceItem("orchestrated_conversation")
    view = ChoiceItem("view")
    interview = ChoiceItem("interview")
    single = ChoiceItem("single")
    case = ChoiceItem("case")
    group = ChoiceItem("group")
    dynamic_discussion = ChoiceItem("dynamic_discussion")
    dynamic_discussion_thread = ChoiceItem("dynamic_discussion_thread")
    lesson = ChoiceItem('lesson')
    test_thread = ChoiceItem('test_thread')
    trainer_thread = ChoiceItem('trainer_thread')
    mcq = ChoiceItem('mcq')
    dynamic_mcq = ChoiceItem('dynamic_mcq')


class ScenarioCaseChoices(DjangoChoices):
    simulation = ChoiceItem("simulation")
    role_play = ChoiceItem("role_play")
    interview = ChoiceItem("interview")
    group_meeting = ChoiceItem("group_meeting")
    email = ChoiceItem("email")
    one_on_one_meeting = ChoiceItem("1:1 meeting")
    case_study = ChoiceItem("case_study")
    counseling = ChoiceItem("counseling")
    presentation  = ChoiceItem("presentation")
    dynamic_discussion  = ChoiceItem("dynamic_discussion")
    feedback_role_play = ChoiceItem("feedback_role_play")
    employee_feedback = ChoiceItem('employee_feedback')
    mcq = ChoiceItem('mcq')
    pms = ChoiceItem('pms')
    process_training = ChoiceItem('process_training')
    english_support = ChoiceItem('english_support')
    pitch = ChoiceItem('pitch')
    assessment = ChoiceItem('assessment')
    psychometric = ChoiceItem('psychometric')
    game = ChoiceItem('game')
    journaling = ChoiceItem('journaling')
    observation = ChoiceItem("observation")   # couldn't attempt this type of test just to observe
    others = ChoiceItem("others")  # for any other type of test that doesn't fit in above categories


class TagChoices(DjangoChoices):
    assessment = ChoiceItem("assessment")
    general = ChoiceItem("general")
class PersonalityModelChoices(DjangoChoices):
    sixteen_factor_discussion = ChoiceItem('sixteen_factor_discussion')
    disc_parameter_discussion = ChoiceItem('disc_parameter_discussion')
    belbin = ChoiceItem('belbin')
    blanchard = ChoiceItem('blanchard')
    big_5 = ChoiceItem('big_5')

class PageNameChoices(DjangoChoices):
    leadership_library = ChoiceItem('leadership_library')
    domain_skills_library = ChoiceItem('domain_skills_library')

class InteractionModeChoices(DjangoChoices):
    text = ChoiceItem("text")
    audio = ChoiceItem("audio")
    video = ChoiceItem("video")
    any   = ChoiceItem("any")


class TestAttemptSessionStatusChoices(DjangoChoices):
    in_progress = ChoiceItem("in_progress")
    completed = ChoiceItem("completed")
    cancelled = ChoiceItem("cancelled")


class QuestionTypeChoices(DjangoChoices):
    subjective = ChoiceItem("subjective")
    objective = ChoiceItem("objective")
    mcq = ChoiceItem("mcq")


class QuestionForChoices(DjangoChoices):
    bot_llm = ChoiceItem("bot_llm")
    user = ChoiceItem("user")

class TestCaseChoices(DjangoChoices):
    hard_skills = ChoiceItem("hard_skills")
    soft_skills = ChoiceItem("soft_skills")
    report = ChoiceItem("report")


class QuestionResponseTypeChoices(DjangoChoices):
    text = ChoiceItem("text")
    audio = ChoiceItem("audio")
    video = ChoiceItem("video")


class TestQuestionResponseEvaluationStatusChoices(DjangoChoices):
    init = ChoiceItem("init")
    in_progress = ChoiceItem("in_progress")
    success = ChoiceItem("success")
    failed = ChoiceItem("failed")


def default_page_config():
    return {"show_lists": True, 
            "show_search": True, 
            "show_filters": "Industry, Function, Unexpected Outcomes, Implementation Complexity,  Business Outcome,Emerging Players"
            }