# Generated by Django 4.1.7 on 2023-04-09 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.TextField()),
                ('subdomain_prefix', models.CharField(max_length=255, unique=True)),
                ('subscription', models.CharField(choices=[('enabled', 'enabled'), ('paused', 'paused'), ('discontinued', 'discontinued')], default='paused', max_length=255)),
            ],
            options={
                'db_table': 'tenant',
                'ordering': ('-id',),
            },
        ),
    ]
