# Generated by Django 4.1.7 on 2023-10-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_is_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='mobile_number_list',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mobile_number_restriction_whatsapp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
