# Generated by Django 4.1.7 on 2023-09-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_is_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="test_per_month",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
