# Generated by Django 4.1.7 on 2023-09-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_test_per_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
