# Generated by Django 4.1.7 on 2023-11-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_mobile_number_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='web_test_code_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
