# Generated by Django 4.1.7 on 2024-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_web_test_code_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='use_skills_from_skill_bank',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
