# Generated by Django 4.1.7 on 2024-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_use_skills_from_skill_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='use_skills_from_skill_bank',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
