# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_tenant_use_skills_from_skill_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
