# Generated by Django 4.1.7 on 2025-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='document_storage_bucket_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
