# Generated by Django 4.1.7 on 2025-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_tenant_document_storage_bucket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='conversation_per_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
