# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
