# Generated by Django 4.1.7 on 2025-08-15 06:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('validation_prompt', models.TextField(verbose_name='Validation Prompt')),
                ('report_generation_prompt', models.TextField(verbose_name='Report Generation Prompt')),
            ],
            options={
                'verbose_name': 'Job Aid',
                'verbose_name_plural': 'Job Aids',
            },
        ),
        migrations.CreateModel(
            name='JobAidSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20, verbose_name='Status')),
                ('generated_report_data', models.JSONField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='jobaid.jobaid', verbose_name='Job Aid')),
            ],
            options={
                'verbose_name': 'Job Aid Session',
                'verbose_name_plural': 'Job Aid Sessions',
            },
        ),
        migrations.CreateModel(
            name='JobAidQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('dropdown', 'Dropdown'), ('boolean', 'Boolean')], default='text', max_length=20, verbose_name='Question Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('dropdowns', models.TextField(blank=True, help_text='Comma-separated values (only if type is dropdown)', null=True)),
                ('job_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobaid.jobaid', verbose_name='Job Aid')),
            ],
            options={
                'verbose_name': 'Job Aid Question',
                'verbose_name_plural': 'Job Aid Questions',
            },
        ),
    ]
