# Generated by Django 4.1.7 on 2025-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaidquestion',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section'),
        ),
    ]
