# Generated by Django 4.1.7 on 2025-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0002_jobaidquestion_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaidsession',
            name='qna',
            field=models.JSONField(blank=True, help_text='Q&A data for the session', null=True),
        ),
    ]
