# Generated by Django 4.1.7 on 2025-08-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0003_jobaidsession_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaid',
            name='report_footer',
            field=models.TextField(blank=True, null=True, verbose_name='Report Footer'),
        ),
        migrations.AddField(
            model_name='jobaid',
            name='report_header',
            field=models.TextField(blank=True, null=True, verbose_name='Report Header'),
        ),
    ]
