# Generated by Django 4.1.7 on 2025-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0004_jobaid_report_footer_jobaid_report_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaid',
            name='job_aid_type',
            field=models.CharField(blank=True, choices=[('job_aid', 'Job Aid'), ('form', 'Form')], default='job_aid', max_length=50, null=True, verbose_name='Job Aid Type'),
        ),
        migrations.AlterField(
            model_name='jobaid',
            name='report_footer',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Report Footer'),
        ),
        migrations.AlterField(
            model_name='jobaid',
            name='report_header',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Report Header'),
        ),
    ]
