# Generated by Django 4.1.7 on 2025-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0006_jobaidquestion_validation_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaidquestion',
            name='validation_prompt',
            field=models.TextField(default='\nValidator Trigger: The system analyzes the input for vagueness or lack of a clear action verb.\nEvaluation Criteria: Assess the user\'s response against these standards:\nLength & Detail: Contains sufficient information to be actionable (minimum 2-3 sentences for most business questions)\nSpecificity: Includes concrete details, examples, or data rather than generic statements\nProfessional Relevance: Demonstrates understanding appropriate to a corporate environment\nCompleteness: Addresses the core components of the question asked\nAuthenticity: Reflects genuine effort rather than placeholder or dismissive content\nResponse Format:\nIf UNACCEPTABLE:\nNOT ACCEPTABLE: [Specific reason - e.g., "Response lacks concrete details and actionable information."] \nIMPROVEMENT GUIDANCE: [30-50 words explaining exactly what needs to be added - e.g., "Please include specific examples, relevant metrics, stakeholder involvement, timeline considerations, or implementation steps. Add context about your role/department and explain the business impact or rationale behind your answer."]\nIf ACCEPTABLE:\nACCEPTABLE\nENHANCEMENT SUGGESTIONS: [2-3 specific recommendations to elevate the response - e.g., "Consider adding: (1) success metrics or KPIs, (2) potential risks and mitigation strategies, (3) stakeholder alignment requirements, (4) resource allocation details."]\nRed Flags for "NOT ACCEPTABLE":\nOne-word answers or single generic sentences\nResponses like "I don\'t know," "N/A," "Not applicable" without explanation\nCopy-paste corporate jargon without substance\nAnswers that could apply to any company/situation without modification\nObvious placeholder text or joke responses\nResponses that don\'t actually answer the question asked\n        ', verbose_name='Validation Prompt'),
        ),
    ]
