# Generated by Django 4.1.7 on 2025-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0008_jobaidsession_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaidsession',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
