# Generated by Django 4.1.7 on 2025-09-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0009_alter_jobaidsession_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaid',
            name='is_validation',
            field=models.BooleanField(default=True, verbose_name='Is Validation'),
        ),
    ]
