# Generated by Django 4.1.7 on 2025-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0010_jobaid_is_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaidsession',
            name='liked_by',
            field=models.TextField(blank=True, help_text='Comma-separated list of user emails who liked the session', null=True),
        ),
    ]
