# Generated by Django 4.1.7 on 2025-10-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0012_jobaid_evaluate_jobaid_jobaid_evaluation_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaid',
            name='evaluate_jobaid',
            field=models.BooleanField(default=False, verbose_name='Evaluation Jobaid'),
        ),
    ]
