# Generated by Django 4.1.7 on 2025-12-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0014_jobaid_is_report_alter_jobaid_evaluation_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaid',
            name='is_prompt_generation',
            field=models.BooleanField(default=True, verbose_name='Is Prompt Generation'),
        ),
        migrations.AddField(
            model_name='jobaid',
            name='prompt_generation_prompt',
            field=models.TextField(blank=True, default='\n      You are the Prompt Generator Engine.\n\nBased on the fields the user provided, generate a single optimized prompt for an AI system.\n\nHere are the user inputs:\n- Objective: {{objective}}\n- Context: {{context}}\n- User Role: {{user_role}}\n- Target Audience: {{target_audience}}\n- Task Type: {{task_type}}\n- Constraints: {{constraints}}\n- Tone: {{tone}}\n- Output Format: {{output_format}}\n- Industry: {{industry}}\n- Success Criteria: {{success_criteria}}\n\nGenerate a **final prompt** that:\n\n1. Starts with a **clear role instruction** (e.g., “Act as an expert in ___”).\n2. Reflects the **objective** as the primary anchor.\n3. Uses contextual details only if provided.\n4. Incorporates user role, audience, task type, tone, constraints, and output format naturally.\n5. Does *not* force information that was not provided.\n6. Ends with a short checklist: “Make sure to…” aligned to the success criteria.\n\nThe output should be only the final optimized prompt — no explanations.\n\n        ', null=True, verbose_name='Prompt Generation'),
        ),
        migrations.AlterField(
            model_name='jobaid',
            name='job_aid_type',
            field=models.CharField(blank=True, choices=[('job_aid', 'Job Aid'), ('form', 'Form'), ('prompt_generator', 'Prompt Generator')], default='job_aid', max_length=50, null=True, verbose_name='Job Aid Type'),
        ),
    ]
