# Generated by Django 4.1.7 on 2025-12-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0015_jobaid_is_prompt_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaidsession',
            name='generated_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
