# Generated by Django 4.1.7 on 2025-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0016_jobaidsession_generated_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaid',
            name='prompt_generation_prompt',
            field=models.TextField(blank=True, default='\n      You are the Prompt Generator Engine.\n\nBased on the fields the user provided, generate a single optimized prompt for an AI system.\n\n\nGenerate a **final prompt** that:\n\n1. Starts with a **clear role instruction** (e.g., “Act as an expert in ___”).\n2. Reflects the **objective** as the primary anchor.\n3. Uses contextual details only if provided.\n4. Incorporates user role, audience, task type, tone, constraints, and output format naturally.\n5. Does *not* force information that was not provided.\n6. Ends with a short checklist: “Make sure to…” aligned to the success criteria.\n\nThe output should be only the final optimized prompt — no explanations.\n\n        ', null=True, verbose_name='Prompt Generation'),
        ),
        migrations.AlterField(
            model_name='jobaidsession',
            name='generated_prompt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
