# Generated by Django 4.1.7 on 2026-01-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0017_alter_jobaid_prompt_generation_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaidsession',
            name='client_id',
            field=models.CharField(blank=True, help_text='Identifier for the client associated with this session', max_length=255, null=True, verbose_name='Client ID'),
        ),
    ]
