# Generated by Django 4.1.7 on 2026-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0018_jobaidsession_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaidquestion',
            name='allow_custom_text',
            field=models.BooleanField(default=False, help_text='Users can enter values not in predefined options', verbose_name='Allow custom input'),
        ),
        migrations.AddField(
            model_name='jobaidquestion',
            name='is_multi_select',
            field=models.BooleanField(default=False, help_text='Enable only for dropdown fields', verbose_name='Multi-select'),
        ),
    ]
