# Generated by Django 4.1.7 on 2026-02-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0020_alter_jobaid_report_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaidquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('dropdown', 'Dropdown'), ('boolean', 'Boolean'), ('editable', 'Editable')], default='text', max_length=20, verbose_name='Question Type'),
        ),
    ]
