# Generated by Django 4.1.7 on 2026-02-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0146_alter_clientresource_options'),
        ('jobaid', '0021_alter_jobaidquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaidsession',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='jobaid_sessions', to='users.clientresource'),
        ),
    ]
