# Generated by Django 4.1.7 on 2026-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0022_jobaidsession_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaidquestion',
            name='attachment_allowed',
            field=models.BooleanField(default=False, help_text='Users can upload a file as an answer', verbose_name='Allow file upload'),
        ),
        migrations.AddField(
            model_name='jobaidsession',
            name='file_qna',
            field=models.JSONField(blank=True, help_text='Q&File data for the session', null=True),
        ),
    ]
