# Generated by Django 4.1.7 on 2026-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0024_alter_jobaid_evaluation_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaid',
            name='custom_prompt',
            field=models.TextField(blank=True, default=None, help_text='Used for transformation programs where the prompt is dynamic based on user input', null=True, verbose_name='Custom Prompt'),
        ),
        migrations.AddField(
            model_name='jobaid',
            name='output',
            field=models.TextField(blank=True, default=None, help_text='Stores the output generated for transformation programs', null=True, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='jobaid',
            name='job_aid_type',
            field=models.CharField(blank=True, choices=[('job_aid', 'Job Aid'), ('form', 'Form'), ('prompt_generator', 'Prompt Generator'), ('transformation_program', 'Transformation Program')], default='job_aid', max_length=50, null=True, verbose_name='Job Aid Type'),
        ),
    ]
