# Generated by Django 4.1.7 on 2026-03-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0025_jobaid_custom_prompt_jobaid_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobaid',
            name='output',
        ),
        migrations.AddField(
            model_name='jobaidsession',
            name='output',
            field=models.TextField(blank=True, default=None, help_text='Stores the output generated for transformation programs', null=True, verbose_name='Output'),
        ),
    ]
