# Generated by Django 4.1.7 on 2026-03-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0026_remove_jobaid_output_jobaidsession_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaid',
            name='labels',
            field=models.JSONField(blank=True, default=dict, help_text="Custom labels for the job aid, e.g. {'Innovation Score': 'Align Priority'}", null=True, verbose_name='Labels'),
        ),
    ]
