# Generated by Django 4.1.7 on 2026-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0027_jobaid_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaid',
            name='labels',
            field=models.JSONField(blank=True, default={'Innovation Score': 'Align Priority'}, help_text="Custom labels for the job aid, e.g. {'Innovation Score': 'Align Priority'}", null=True, verbose_name='Labels'),
        ),
    ]
