# Generated by Django 4.1.7 on 2026-03-16 05:16

from django.db import migrations, models
import jobaid.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0028_alter_jobaid_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaid',
            name='session_voting_enabled',
            field=models.BooleanField(default=True, help_text='Allow users to like or dislike their session after completion', verbose_name='Session Voting Enabled'),
        ),
        migrations.AlterField(
            model_name='jobaid',
            name='labels',
            field=models.JSONField(blank=True, default=jobaid.models.default_labels, help_text="Custom labels for the job aid, e.g. {'Innovation Score': {'label':'Align Priority', 'info': 'xyz'} }", null=True, verbose_name='Labels'),
        ),
    ]
