# Generated by Django 4.1.7 on 2023-04-28 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('test_attempt_session_id', models.CharField(db_index=True, max_length=255)),
                ('coach_message_text', models.TextField()),
                ('coach_message_metadata', models.JSONField(blank=True, default=None, null=True)),
                ('participant_message_url', models.TextField(blank=True, default=None, null=True)),
                ('participant_message_text', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('bot_message_saved', 'bot message saved'), ('participant_message_saved', 'participant message saved'), ('conversation_finished', 'conversation finished')], default='bot_message_saved', max_length=255)),
            ],
            options={
                'db_table': 'coaching_conversation',
            },
        ),
    ]
