# Generated by Django 4.1.7 on 2023-05-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachingconversation',
            options={'ordering': ('-id',)},
        ),
    ]
