# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_conversations', '0002_alter_coachingconversation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingconversation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
