# Generated by Django 4.1.7 on 2025-08-05 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_conversations', '0003_alter_coachingconversation_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotResponsePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
