class Skills:
    TEAMWORK = 'teamwork'
    LEADERSHIP = 'leadership'
    PEOPLE_MANAGEMENT = 'people management'
    CONFLICT_MANAGEMENT = 'conflict management'
    NEGOTIATION = 'negotiation'
    STRATEGIC_THINKING = 'strategic thinking'
    PROJECT_MANAGEMENT = 'project management'
    TIME_MANAGEMENT = 'time management'
    ADAPTABILITY = 'adaptability'
    ENGAGEMENT = 'engagement'
    EMPATHY = 'empathy'
    COMMUNICATION = 'communication'
    CONFIDENCE = 'confidence'
    CLARITY = 'clarity'
    