# Generated by Django 4.1.7 on 2024-08-30 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('mailbox_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'email_conversation',
            },
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'mail_box',
                'unique_together': {('email', 'deleted')},
            },
        ),
        migrations.CreateModel(
            name='AuthorizedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('user_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_black_list', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'authorized_emails',
                'unique_together': {('email', 'deleted')},
            },
        ),
    ]
