# Generated by Django 4.1.7 on 2024-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconversation',
            name='response_type',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
