# Generated by Django 4.1.7 on 2024-08-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0002_emailconversation_response_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconversation',
            old_name='response_type',
            new_name='responder',
        ),
    ]
