# Generated by Django 4.1.7 on 2024-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0003_rename_response_type_emailconversation_responder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='followup_prompt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
