# Generated by Django 4.1.7 on 2024-09-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0004_mailbox_followup_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedemails',
            name='is_whitelist',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='document_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
