# Generated by Django 4.1.7 on 2024-09-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0005_authorizedemails_is_whitelist_mailbox_document_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedemails',
            name='age',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorizedemails',
            name='followup_escalation_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorizedemails',
            name='followup_fequency',
            field=models.CharField(blank=True, choices=[('weekly', 'weekly'), ('daily', 'daily'), ('monthly', 'monthly'), ('nan', 'nan')], default='nan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorizedemails',
            name='goal',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorizedemails',
            name='mailbox_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='authorizedemails',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorizedemails',
            name='reward_emails',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizedemails',
            name='situation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='followup_prompt2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='reward_prompt1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='reward_prompt2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
