# Generated by Django 4.1.7 on 2024-09-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0006_authorizedemails_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='grant_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
