# Generated by Django 4.1.7 on 2024-09-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0007_mailbox_grant_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorizedemails',
            unique_together={('mailbox_id', 'email', 'deleted')},
        ),
    ]
