# Generated by Django 4.1.7 on 2024-09-07 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0007_mailbox_grant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountabilityIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('form_id', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('submission_number', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('submission_id', models.CharField(max_length=50)),
                ('form_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('competency_level', models.CharField(max_length=50)),
                ('follow_up_frequency', models.CharField(choices=[('weekly', 'weekly'), ('daily', 'daily'), ('monthly', 'monthly'), ('nan', 'nan')], default='nan', max_length=255)),
                ('followup_escalation_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('wants_rewards', models.BooleanField()),
                ('overall_goals', models.TextField()),
                ('situational_context', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
