# Generated by Django 4.1.7 on 2024-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0008_accountabilityintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountabilityintake',
            name='event_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountabilityintake',
            name='form_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountabilityintake',
            name='form_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountabilityintake',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accountabilityintake',
            name='submission_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
