# Generated by Django 4.1.7 on 2024-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0009_alter_accountabilityintake_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='followup_prompt3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
