# Generated by Django 4.1.7 on 2024-09-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0008_alter_authorizedemails_unique_together'),
        ('mail_box', '0010_mailbox_followup_prompt3'),
    ]

    operations = [
    ]
