# Generated by Django 4.1.7 on 2024-09-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0011_merge_20240917_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedemails',
            name='is_intake_filled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='bot_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='intake_reminder_email_template',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='intake_required',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='intake_url',
            field=models.CharField(blank=True, default='https://chat.coachbots.com/66dc18ab01ef84e231427f7b', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='welcome_email_template',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accountabilityintake',
            name='follow_up_frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('daily', 'daily'), ('monthly', 'monthly'), ('nan', 'nan'), ('never', 'never'), ('alternate', 'alternate')], default='nan', max_length=255),
        ),
        migrations.AlterField(
            model_name='authorizedemails',
            name='followup_fequency',
            field=models.CharField(blank=True, choices=[('weekly', 'weekly'), ('daily', 'daily'), ('monthly', 'monthly'), ('nan', 'nan'), ('never', 'never'), ('alternate', 'alternate')], default='never', max_length=255, null=True),
        ),
    ]
