# Generated by Django 4.1.7 on 2024-10-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0012_authorizedemails_is_intake_filled_mailbox_bot_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='bot_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='grant_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
