# Generated by Django 4.1.7 on 2024-10-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0013_alter_mailbox_bot_name_alter_mailbox_grant_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountabilityintake',
            unique_together={('form_id', 'email_address', 'deleted')},
        ),
    ]
