# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0014_alter_accountabilityintake_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountabilityintake',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authorizedemails',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailconversation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
