# Generated by Django 4.1.7 on 2025-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0015_alter_accountabilityintake_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='knowledge_base',
            field=models.TextField(blank=True, default=None, help_text='Knowledge base for the mailbox, can be used to store pdf and docx url can be comma separated.', null=True),
        ),
    ]
