# Generated by Django 4.1.7 on 2023-04-18 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.TextField()),
                ('object_id', models.TextField()),
                ('bucket_name', models.TextField()),
                ('region_name', models.TextField()),
                ('doc_type', models.CharField(choices=[('AUDIO_ANSWER', 'AUDIO ANSWER'), ('VIDEO_ANSWER', 'VIDEO ANSWER')], max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('owner_type', models.CharField(choices=[('user', 'user'), ('system', 'system')], max_length=255)),
                ('owner_id', models.CharField(db_index=True, max_length=255)),
                ('transcript_details', models.JSONField(blank=True, null=True)),
                ('doc_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'document',
                'ordering': ('id',),
            },
        ),
    ]
