# Generated by Django 4.1.7 on 2023-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('AUDIO_ANSWER', 'AUDIO ANSWER'), ('VIDEO_ANSWER', 'VIDEO ANSWER'), ('FLASH_CARD', 'FLASH CARD')], max_length=255),
        ),
    ]
