# Generated by Django 4.1.7 on 2023-05-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('AUDIO_ANSWER', 'AUDIO ANSWER'), ('VIDEO_ANSWER', 'VIDEO ANSWER'), ('FLASH_CARD', 'FLASH CARD'), ('MIND_MAP', 'MIND MAP'), ('REPORT', 'REPORT'), ('PARTICIPANT_REPORT', 'PARTICIPANT REPORT')], max_length=255),
        ),
    ]
