# Generated by Django 4.1.7 on 2023-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='actions_pipeline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
