# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_actions_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
