# Generated by Django 4.1.7 on 2024-09-25 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('thread_id', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('assistant', 'assistant'), ('user', 'user')], max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chat_conversation',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('bot_id', models.CharField(max_length=100)),
                ('thread_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('chat_topic', models.TextField()),
            ],
            options={
                'db_table': 'legacybot_thread',
                'unique_together': {('bot_id', 'thread_id', 'user_id', 'deleted')},
            },
        ),
        migrations.CreateModel(
            name='LegacyBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('bot_id', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('att', models.JSONField(blank=True, default=None, null=True)),
                ('is_whitelist', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'single_bot_user',
                'unique_together': {('bot_id', 'email', 'deleted')},
            },
        ),
        migrations.CreateModel(
            name='LegacyBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('domain', models.CharField(max_length=100)),
                ('assistant_id', models.CharField(max_length=100)),
                ('assitant_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('prompt', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'single_bot',
                'unique_together': {('domain', 'assistant_id', 'deleted')},
            },
        ),
    ]
