# Generated by Django 4.1.7 on 2024-10-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='action_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
