# Generated by Django 4.1.7 on 2024-10-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0002_thread_action_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybot',
            name='att',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='legacybot',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legacybotuser',
            name='preferences',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='preferences',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
