# Generated by Django 4.1.7 on 2024-11-05 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0003_legacybot_att_legacybot_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybot',
            name='bot_identifier',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='legacybot',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_bot', to='legacybot.legacybotuser'),
        ),
        migrations.AlterModelTable(
            name='legacybot',
            table='legacy_bot',
        ),
        migrations.AlterModelTable(
            name='legacybotuser',
            table='legacy_bot_user',
        ),
        migrations.CreateModel(
            name='LegacyBotRoleAndPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('role', models.CharField(choices=[('premimum', 'premimum'), ('demo', 'demo')], max_length=125)),
                ('max_session', models.IntegerField(blank=True, default=10, null=True)),
            ],
            options={
                'db_table': 'legacy_bot_role_and_permission',
                'unique_together': {('role', 'deleted')},
            },
        ),
        migrations.AddField(
            model_name='legacybotuser',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='legacybot.legacybotroleandpermissions'),
        ),
    ]
