# Generated by Django 4.1.7 on 2024-11-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0006_update_user_with_nonerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybot',
            name='asst_meta_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='legacybot',
            name='vector_store_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='legacybot',
            name='bot_identifier',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
