# Generated by Django 4.1.7 on 2024-11-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0007_legacybot_asst_meta_data_legacybot_vector_store_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legacybotuser',
            name='role',
        ),
        migrations.AddField(
            model_name='legacybotuser',
            name='max_session',
            field=models.IntegerField(blank=True, default=10, help_text='Maximum number of sessions. Set to -1 for unlimited sessions.', null=True),
        ),
        migrations.AddField(
            model_name='legacybotuser',
            name='session_per_conversation_step',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='This represents how many conv step a session will contain.', null=True),
        ),
        migrations.AlterField(
            model_name='legacybotroleandpermissions',
            name='max_session',
            field=models.IntegerField(blank=True, default=10, help_text='Maximum number of sessions. Set to -1 for unlimited sessions.', null=True),
        ),
        migrations.AlterField(
            model_name='legacybotroleandpermissions',
            name='role',
            field=models.CharField(choices=[('premimum', 'premimum'), ('demo', 'demo')], help_text='Select the role for the bot.', max_length=125),
        ),
    ]
