# Generated by Django 4.1.7 on 2024-11-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0008_remove_legacybotuser_role_legacybotuser_max_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacybot',
            name='vector_store_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
