# Generated by Django 4.1.7 on 2024-11-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0009_alter_legacybot_vector_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybot',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='legacybotuser',
            name='bot_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LegacyBotUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_and_conversation_info', models.JSONField(blank=True, default=dict, help_text='Stores JSON data for threads and conversations associated with this user-bot mapping.', null=True)),
                ('total_thread', models.PositiveIntegerField(blank=True, default=0, help_text='Total count of threads for this user-bot mapping.', null=True)),
                ('total_conversation', models.PositiveIntegerField(blank=True, default=0, help_text='Total count of conversations for this user-bot mapping.', null=True)),
                ('total_session', models.PositiveIntegerField(blank=True, default=0, help_text='Total count of sessions for this user-bot mapping.', null=True)),
                ('bot', models.ForeignKey(help_text='Reference to the legacy bot.', on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='legacybot.legacybot')),
                ('user', models.ForeignKey(help_text='Reference to the legacy bot user.', on_delete=django.db.models.deletion.CASCADE, related_name='bot_mappings', to='legacybot.legacybotuser')),
            ],
            options={
                'verbose_name': 'Legacy Bot User Mapping',
                'verbose_name_plural': 'Legacy Bot User Mappings',
                'db_table': 'legacy_bot_user_mapping',
            },
        ),
        migrations.AddIndex(
            model_name='legacybotusermapping',
            index=models.Index(fields=['user', 'bot'], name='legacy_bot__user_id_929cd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legacybotusermapping',
            unique_together={('user', 'bot')},
        ),
    ]
