# Generated by Django 4.1.7 on 2024-11-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0010_legacybot_is_published_alter_legacybotuser_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legacybotuser',
            unique_together={('email', 'deleted')},
        ),
    ]
