# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0011_alter_legacybotuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legacybot',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legacybotroleandpermissions',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legacybotuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
