# Generated by Django 4.1.7 on 2025-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0012_alter_chatconversation_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybotuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='legacybotuser',
            name='role',
            field=models.CharField(blank=True, choices=[('premimum', 'premimum'), ('freemium', 'freemium')], default='freemium', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legacybotroleandpermissions',
            name='role',
            field=models.CharField(choices=[('premimum', 'premimum'), ('freemium', 'freemium')], help_text='Select the role for the bot.', max_length=125),
        ),
        migrations.AlterField(
            model_name='legacybotuser',
            name='max_session',
            field=models.IntegerField(blank=True, default=10, help_text='Maximum number of sessions. Set to -1 for unlimited sessions. if you choose role Premimum it will considered -1.', null=True),
        ),
    ]
