# Generated by Django 4.1.7 on 2025-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0013_legacybotuser_is_active_legacybotuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybot',
            name='buttons',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='legacybot',
            name='report_info',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='legacybot',
            name='show_report',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='legacybot',
            name='stream',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='legacybot',
            name='welcome_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
