# Generated by Django 4.1.7 on 2025-02-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0014_legacybot_buttons_legacybot_report_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacybot',
            name='buttons',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='legacybot',
            name='stream',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
