# Generated by Django 4.1.7 on 2025-02-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0015_alter_legacybot_buttons_alter_legacybot_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacybot',
            name='buttons',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
