# Generated by Django 4.1.7 on 2025-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacybot', '0016_alter_legacybot_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybot',
            name='max_session',
            field=models.IntegerField(blank=True, default=1, help_text='Maximum number of sessions.', null=True),
        ),
        migrations.AddField(
            model_name='legacybot',
            name='session_per_conversation_step',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='This represents how many conv step a session will contain.', null=True),
        ),
        migrations.AlterField(
            model_name='legacybotuser',
            name='max_session',
            field=models.IntegerField(blank=True, default=-1, help_text='Maximum number of sessions. if -1 then Main legacybot session config will be considered.', null=True),
        ),
    ]
