# Generated by Django 4.1.7 on 2023-04-09 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('creator_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('interaction_mode', models.CharField(choices=[('text', 'text'), ('audio', 'audio'), ('video', 'video')], max_length=255)),
                ('is_trainer_mode_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='TestAttemptSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('test_id', models.CharField(db_index=True, max_length=255)),
                ('participant_id', models.CharField(db_index=True, max_length=255)),
                ('test_invite_id', models.CharField(max_length=255, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='in_progress', max_length=255)),
            ],
            options={
                'db_table': 'test_attempt_session',
            },
        ),
        migrations.CreateModel(
            name='TestInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('test_id', models.CharField(db_index=True, max_length=255)),
                ('participant_id', models.CharField(db_index=True, max_length=255)),
                ('expires_at', models.DateTimeField(default=None, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'test_invite',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('test_id', models.CharField(db_index=True, max_length=255)),
                ('question_type', models.CharField(choices=[('subjective', 'subjective'), ('objective', 'objective'), ('mcq', 'mcq')], max_length=255)),
                ('media_link', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('subjective_answer', models.TextField(blank=True, null=True)),
                ('objective_answer', models.TextField(blank=True, null=True)),
                ('mcq_options', models.JSONField(blank=True, null=True)),
                ('mcq_answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_question',
            },
        ),
        migrations.CreateModel(
            name='TestQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('test_attempt_session_id', models.CharField(db_index=True, max_length=255)),
                ('question_id', models.CharField(db_index=True, max_length=255)),
                ('response_file', models.TextField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('evaluation_status', models.CharField(choices=[('init', 'init'), ('in_progress', 'in progress'), ('success', 'success'), ('failed', 'failed')], default='init', max_length=255)),
            ],
            options={
                'db_table': 'test_question_response',
                'unique_together': {('test_attempt_session_id', 'question_id')},
            },
        ),
    ]
