# Generated by Django 4.1.7 on 2023-04-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testquestionresponse',
            unique_together={('test_attempt_session_id', 'question_id', 'deleted')},
        ),
        migrations.AddField(
            model_name='testquestionresponse',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
