# Generated by Django 4.1.7 on 2023-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_testquestionresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='gpt_prompt_override',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='gpt_prompt_override',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
