# Generated by Django 4.1.7 on 2023-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_gpt_prompt_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_code',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
