# Generated by Django 4.1.7 on 2023-05-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_test_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('tenant_id', 'test_code', 'deleted')},
        ),
    ]
