# Generated by Django 4.1.7 on 2023-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_test_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='key_learning_point',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='key_learning_skills',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
