# Generated by Django 4.1.7 on 2023-05-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_testquestion_key_learning_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='flash_card_doc_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
