# Generated by Django 4.1.7 on 2023-05-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_testquestion_flash_card_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mindmap_doc_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
