# Generated by Django 4.1.7 on 2023-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_test_mindmap_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='report_doc_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
