# Generated by Django 4.1.7 on 2023-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0009_testattemptsession_report_doc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="flash_card_doc_id",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
