# Generated by Django 4.1.7 on 2023-05-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0010_test_flash_card_doc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattemptsession",
            name="skills_rating",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="testquestionresponse",
            name="skills_rating",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
