# Generated by Django 4.1.7 on 2023-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0011_testattemptsession_skills_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattemptsession",
            name="test_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
