# Generated by Django 4.1.7 on 2023-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_testattemptsession_test_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testattemptsession',
            index=models.Index(fields=['tenant_id', 'test_id', 'test_score'], name='test_attemp_tenant__47f2db_idx'),
        ),
    ]
