# Generated by Django 4.1.7 on 2023-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0013_testattemptsession_test_attemp_tenant__47f2db_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattemptsession",
            name="culture_skills_rating",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
