# Generated by Django 4.1.7 on 2023-06-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_testattemptsession_culture_skills_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestionresponse',
            name='speech_metrics',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
