# Generated by Django 4.1.7 on 2023-06-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_testquestionresponse_speech_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='speech_score',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
