# Generated by Django 4.1.7 on 2023-06-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_testattemptsession_speech_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='avg_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestionresponse',
            name='avg_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
