# Generated by Django 4.1.7 on 2023-06-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_testattemptsession_avg_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
