# Generated by Django 4.1.7 on 2023-06-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_test_orchestrated_conversation_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question_for',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='testquestionresponse',
            name='responder_type',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
