# Generated by Django 4.1.7 on 2023-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_alter_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='email_address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='send_only_to_email',
            field=models.BooleanField(default=False),
        ),
    ]
