# Generated by Django 4.1.7 on 2023-06-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_test_email_address_test_send_only_to_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='email_address',
            new_name='email_address_list',
        ),
    ]
