# Generated by Django 4.1.7 on 2023-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_rename_email_address_test_email_address_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='email_candidate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='send_only_to_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
