# Generated by Django 4.1.7 on 2023-06-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_test_email_candidate_alter_test_send_only_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='candidate_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
