# Generated by Django 4.1.7 on 2023-06-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_test_candidate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='orchestrated_conversation_details',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='can_be_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='is_view_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='loader_wait_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_for',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='testquestionresponse',
            name='responder_display_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestionresponse',
            name='responder_type',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('test', 'test'), ('trainer', 'trainer'), ('coaching', 'coaching'), ('orchestrated_conversation', 'orchestrated conversation')], default='trainer', max_length=255),
        ),
    ]
