# Generated by Django 4.1.7 on 2023-06-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_test_orchestrated_conversation_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='areas_of_improvement',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='meeting_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
