# Generated by Django 4.1.7 on 2023-06-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_testattemptsession_areas_of_improvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description_media',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('test', 'test'), ('trainer', 'trainer'), ('coaching', 'coaching'), ('orchestrated_conversation', 'orchestrated conversation'), ('view', 'view'), ('interview', 'interview'), ('single', 'single'), ('case', 'case'), ('group', 'group')], default='trainer', max_length=255),
        ),
    ]
