# Generated by Django 4.1.7 on 2023-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_test_description_media_alter_test_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_test_allowed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
