# Generated by Django 4.1.7 on 2023-07-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_test_max_test_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='is_report_sent_to_email',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='is_report_sent_to_whatsapp',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='report_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
