# Generated by Django 4.1.7 on 2023-07-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_testattemptsession_is_report_sent_to_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='current_question_idx',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='next_question_idx',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
