# Generated by Django 4.1.7 on 2023-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_testattemptsession_is_report_sent_to_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_single_bot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
