# Generated by Django 4.1.7 on 2023-07-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_testattemptsession_current_question_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_single_bot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
