# Generated by Django 4.1.7 on 2023-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_test_is_single_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_checkin_type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_learner_path',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='skills_to_evaluate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
