# Generated by Django 4.1.7 on 2023-07-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_test_is_checkin_type_test_is_learner_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='is_checkin_type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
