# Generated by Django 4.1.7 on 2023-07-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_testattemptsession_is_checkin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tedtalk_and_hbr_case',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
