# Generated by Django 4.1.7 on 2023-07-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_test_tedtalk_and_hbr_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_email_type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
