# Generated by Django 4.1.7 on 2023-07-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_test_is_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting')], default='simulation', max_length=255),
        ),
    ]
