# Generated by Django 4.1.7 on 2023-07-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_alter_test_scenario_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(blank=True, choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling')], default='simulation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testattemptsession',
            name='areas_of_improvement',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
