# Generated by Django 4.1.7 on 2023-08-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0036_alter_test_scenario_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestionresponse',
            name='relevance',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
