# Generated by Django 4.1.7 on 2023-08-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0037_testquestionresponse_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_game_type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='rating',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='source',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
