# Generated by Django 4.1.7 on 2023-09-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0038_test_image_url_test_is_game_type_test_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(blank=True, choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling'), ('presentation', 'presentation')], default='simulation', max_length=255, null=True),
        ),
    ]
