# Generated by Django 4.1.7 on 2023-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0039_alter_test_scenario_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='rating',
            field=models.TextField(blank=True, default='Not Rated', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='source',
            field=models.TextField(blank=True, default='CoachBot', null=True),
        ),
    ]
