# Generated by Django 4.1.7 on 2023-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0040_alter_test_rating_alter_test_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_repeat',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
