# Generated by Django 4.1.7 on 2023-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0041_test_is_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattemptsession",
            name="culture_skills_explanation",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="testattemptsession",
            name="skills_explanation",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
