# Generated by Django 4.1.7 on 2023-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0043_testattemptsession_culture_skills_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='client_name',
            field=models.CharField(blank=True, default='Demo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('test', 'test'), ('trainer', 'trainer'), ('coaching', 'coaching'), ('orchestrated_conversation', 'orchestrated conversation'), ('view', 'view'), ('interview', 'interview'), ('single', 'single'), ('case', 'case'), ('group', 'group'), ('dynamic_discussion', 'dynamic discussion'), ('lesson', 'lesson')], default='trainer', max_length=255),
        ),
    ]
