# Generated by Django 4.1.7 on 2023-10-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0044_alter_test_test_type'),
        ('tests', '0044_test_client_name_alter_test_test_type'),
    ]

    operations = [
    ]
