# Generated by Django 4.1.7 on 2023-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0045_merge_20231005_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="testquestionresponse",
            name="kls_klp",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
