# Generated by Django 4.1.7 on 2023-10-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0046_testquestionresponse_kls_klp'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='culture_and_skill_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='feedback_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(blank=True, choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling'), ('presentation', 'presentation'), ('dynamic_discussion', 'dynamic discussion')], default='simulation', max_length=255, null=True),
        ),
    ]
