# Generated by Django 4.1.7 on 2023-10-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0047_testattemptsession_culture_and_skill_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="course",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="exp_level",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="goals",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="industry",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
