# Generated by Django 4.1.7 on 2023-10-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0048_test_course_test_exp_level_test_goals_test_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(blank=True, choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling'), ('presentation', 'presentation'), ('dynamic_discussion', 'dynamic discussion'), ('feedback_role_play', 'feedback role play')], default='simulation', max_length=255, null=True),
        ),
    ]
