# Generated by Django 4.1.7 on 2023-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0049_alter_test_scenario_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('test', 'test'), ('trainer', 'trainer'), ('coaching', 'coaching'), ('orchestrated_conversation', 'orchestrated conversation'), ('view', 'view'), ('interview', 'interview'), ('single', 'single'), ('case', 'case'), ('group', 'group'), ('dynamic_discussion', 'dynamic discussion'), ('dynamic_discussion_thread', 'dynamic discussion thread'), ('lesson', 'lesson'), ('test_thread', 'test thread'), ('trainer_thread', 'trainer thread')], default='trainer', max_length=255),
        ),
    ]
