# Generated by Django 4.1.7 on 2023-11-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0050_alter_test_test_type'),
        ('tests', '0050_test_is_free_alter_test_scenario_case_and_more'),
    ]

    operations = [
    ]
