# Generated by Django 4.1.7 on 2023-11-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0051_merge_20231122_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='interaction_mode',
            field=models.CharField(choices=[('text', 'text'), ('audio', 'audio'), ('video', 'video'), ('any', 'any')], max_length=255),
        ),
    ]
