# Generated by Django 4.1.7 on 2023-11-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0052_alter_test_interaction_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='mcq_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='mcq_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestionresponse',
            name='mcq_skill',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(blank=True, choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling'), ('presentation', 'presentation'), ('dynamic_discussion', 'dynamic discussion'), ('feedback_role_play', 'feedback role play'), ('employee_feedback', 'employee feedback'), ('mcq', 'mcq')], default='simulation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('test', 'test'), ('trainer', 'trainer'), ('coaching', 'coaching'), ('orchestrated_conversation', 'orchestrated conversation'), ('view', 'view'), ('interview', 'interview'), ('single', 'single'), ('case', 'case'), ('group', 'group'), ('dynamic_discussion', 'dynamic discussion'), ('dynamic_discussion_thread', 'dynamic discussion thread'), ('lesson', 'lesson'), ('test_thread', 'test thread'), ('trainer_thread', 'trainer thread'), ('mcq', 'mcq')], default='trainer', max_length=255),
        ),
    ]
