# Generated by Django 4.1.7 on 2023-11-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0053_testattemptsession_mcq_summary_testquestion_mcq_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_question',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
