# Generated by Django 4.1.7 on 2023-11-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0054_test_total_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='certificate_details',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
