# Generated by Django 4.1.7 on 2023-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0055_test_certificate_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ui_information',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
