# Generated by Django 4.1.7 on 2023-12-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0056_test_ui_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_self_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
