# Generated by Django 4.1.7 on 2023-12-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0057_test_is_self_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_micro",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
