# Generated by Django 4.1.7 on 2023-12-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0058_test_is_micro'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_logged_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
