# Generated by Django 4.1.7 on 2023-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0059_test_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_immersive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='media_props',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
