# Generated by Django 4.1.7 on 2023-12-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0060_test_is_immersive_test_media_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='competency_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testquestionresponse',
            name='response_rating',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(blank=True, choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling'), ('presentation', 'presentation'), ('dynamic_discussion', 'dynamic discussion'), ('feedback_role_play', 'feedback role play'), ('employee_feedback', 'employee feedback'), ('mcq', 'mcq'), ('pms', 'pms'), ('process_training', 'process training')], default='simulation', max_length=255, null=True),
        ),
    ]
