# Generated by Django 4.1.7 on 2023-12-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0061_testattemptsession_competency_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_transcript_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('test', 'test'), ('trainer', 'trainer'), ('coaching', 'coaching'), ('orchestrated_conversation', 'orchestrated conversation'), ('view', 'view'), ('interview', 'interview'), ('single', 'single'), ('case', 'case'), ('group', 'group'), ('dynamic_discussion', 'dynamic discussion'), ('dynamic_discussion_thread', 'dynamic discussion thread'), ('lesson', 'lesson'), ('test_thread', 'test thread'), ('trainer_thread', 'trainer thread'), ('mcq', 'mcq'), ('dynamic_mcq', 'dynamic mcq')], default='trainer', max_length=255),
        ),
    ]
