# Generated by Django 4.1.7 on 2023-12-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0062_test_is_transcript_only_alter_test_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_pitch",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="testattemptsession",
            name="language_skills",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
