# Generated by Django 4.1.7 on 2024-01-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0063_test_is_pitch_testattemptsession_language_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='articles',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
