# Generated by Django 4.1.7 on 2024-01-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0064_test_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bot_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
