# Generated by Django 4.1.7 on 2024-01-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0065_test_bot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='competency_group',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
