# Generated by Django 4.1.7 on 2024-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0066_test_competency_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='creator_user_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
