# Generated by Django 4.1.7 on 2024-02-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0067_test_creator_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='area_domain',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
