# Generated by Django 4.1.7 on 2024-02-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0068_test_area_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tab_category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
