# Generated by Django 4.1.7 on 2024-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0069_test_tab_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='is_idp_discussion_opted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
