# Generated by Django 4.1.7 on 2024-02-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0070_alter_test_scenario_case'),
        ('tests', '0070_testattemptsession_is_idp_discussion_opted'),
    ]

    operations = [
    ]
