# Generated by Django 4.1.7 on 2024-02-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0071_merge_20240224_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='intake_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
