# Generated by Django 4.1.7 on 2024-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0072_testattemptsession_intake_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
