# Generated by Django 4.1.7 on 2024-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0073_test_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='visual_tags',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
