# Generated by Django 4.1.7 on 2024-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0074_testattemptsession_visual_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattemptsession',
            name='visual_tags',
        ),
        migrations.AddField(
            model_name='test',
            name='visual_tags',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
