# Generated by Django 4.1.7 on 2024-03-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0075_remove_testattemptsession_visual_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='page_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
