# Generated by Django 4.1.7 on 2024-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0076_test_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='scenario_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
