# Generated by Django 4.1.7 on 2024-04-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0077_test_scenario_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='conversation_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='related_previous_conversation_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
