# Generated by Django 4.1.7 on 2024-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0078_testattemptsession_conversation_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='creator_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
