# Generated by Django 4.1.7 on 2024-05-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0079_test_creator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_assigned',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
