# Generated by Django 4.1.7 on 2024-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0080_test_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assigned_to',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
