# Generated by Django 4.1.7 on 2024-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0081_test_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assigned_by',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
