# Generated by Django 4.1.7 on 2024-05-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0082_test_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='web_page_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
