# Generated by Django 4.1.7 on 2024-06-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0083_test_web_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sub_tab_category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
