# Generated by Django 4.1.7 on 2024-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0085_alter_test_scenario_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='calculate_culture',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
