# Generated by Django 4.1.7 on 2024-07-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0086_test_calculate_culture'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='snippet_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='snippet_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
