# Generated by Django 4.1.7 on 2024-08-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0087_test_snippet_url_testquestion_snippet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='is_signature_bot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
