# Generated by Django 4.1.7 on 2024-09-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0089_alter_test_scenario_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pshycometric_sections',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='pshycometric_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(blank=True, choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling'), ('presentation', 'presentation'), ('dynamic_discussion', 'dynamic discussion'), ('feedback_role_play', 'feedback role play'), ('employee_feedback', 'employee feedback'), ('mcq', 'mcq'), ('pms', 'pms'), ('process_training', 'process training'), ('english_support', 'english support'), ('pitch', 'pitch'), ('assessment', 'assessment'), ('psychometric', 'psychometric')], default='simulation', max_length=255, null=True),
        ),
    ]
