# Generated by Django 4.1.7 on 2024-10-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0088_alter_test_scenario_case'),
        ('tests', '0090_test_pshycometric_sections_and_more'),
    ]

    operations = [
    ]
