# Generated by Django 4.1.7 on 2024-10-28 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0092_alter_test_scenario_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'psychometric',
                'unique_together': {('name', 'tenant_id', 'deleted')},
            },
        ),
        migrations.CreateModel(
            name='PsychometricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('subsection', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('range_values', models.JSONField(blank=True, default=dict, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('psychometric_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tests.psychometric')),
            ],
            options={
                'db_table': 'psychometric_item',
            },
        ),
    ]
