# Generated by Django 4.1.7 on 2024-10-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0093_psychometric_psychometricitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychometricitem',
            name='tenant_id',
        ),
    ]
