# Generated by Django 4.1.7 on 2024-10-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0094_remove_psychometricitem_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychometricitem',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='psychometricitem',
            name='strengths',
        ),
        migrations.AddField(
            model_name='test',
            name='psychometric',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='tests.psychometric', to_field='uid'),
        ),
    ]
