# Generated by Django 4.1.7 on 2024-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0095_remove_psychometricitem_areas_for_improvement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychometricitem',
            name='psychometric_set',
        ),
        migrations.AddField(
            model_name='psychometric',
            name='items',
            field=models.ManyToManyField(related_name='psychometrics', to='tests.psychometricitem'),
        ),
    ]
