# Generated by Django 4.1.7 on 2024-11-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0096_remove_psychometricitem_psychometric_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychometric',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='psychometric',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='psychometrics', to='tests.psychometricitem'),
        ),
        migrations.AlterField(
            model_name='psychometric',
            name='tenant_id',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
    ]
