# Generated by Django 4.1.7 on 2024-11-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0097_alter_psychometric_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychometricitem',
            name='average_value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
