# Generated by Django 4.1.7 on 2024-11-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0098_psychometricitem_average_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychometricitem',
            name='average_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
