# Generated by Django 4.1.7 on 2024-11-15 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0101_alter_psychometricitem_average_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('test_code', models.CharField(max_length=12)),
                ('test_title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('access_code', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('user_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('report_on', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_test_configs',
                'unique_together': {('user_email', 'test_code', 'deleted')},
            },
        ),
    ]
