# Generated by Django 4.1.7 on 2024-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0102_usertestconfigs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertestconfigs',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usertestconfigs',
            name='access_code',
            field=models.CharField(blank=True, default=None, help_text='Optional: Enter or generate a unique access code for the test.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usertestconfigs',
            name='report_on',
            field=models.BooleanField(default=True, help_text='Toggle this to enable or disable reporting for the test.'),
        ),
        migrations.AlterField(
            model_name='usertestconfigs',
            name='test_code',
            field=models.CharField(help_text='Enter the unique code for the test (maximum 12 characters).', max_length=12),
        ),
        migrations.AlterField(
            model_name='usertestconfigs',
            name='test_title',
            field=models.CharField(blank=True, default=None, help_text='Optional: Enter the title of the test. It will be auto-populated if left blank.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usertestconfigs',
            name='user_email',
            field=models.EmailField(help_text='Enter the email address of the user. Ensure it is valid.', max_length=254),
        ),
        migrations.AlterField(
            model_name='usertestconfigs',
            name='user_id',
            field=models.CharField(blank=True, default=None, help_text='Optional: Enter the user ID associated with the user email.', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usertestconfigs',
            unique_together={('user_id', 'test_code', 'deleted')},
        ),
    ]
