# Generated by Django 4.1.7 on 2024-11-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0103_alter_usertestconfigs_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='report_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
