# Generated by Django 4.1.7 on 2024-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0104_test_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
