# Generated by Django 4.1.7 on 2024-12-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0105_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestconfigs',
            name='report_on',
            field=models.BooleanField(blank=True, help_text='Toggle this to enable or disable reporting for the test.', null=True),
        ),
    ]
