# Generated by Django 4.1.7 on 2024-12-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0107_testquestionresponse_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_single_select',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
