# Generated by Django 4.1.7 on 2025-01-07 10:45

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0108_test_is_single_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychometricitem',
            name='psychometric',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='psy_items', to='tests.psychometric'),
        )

    ]
