# Generated by Django 4.1.7 on 2025-01-08 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0110_psychometricreportsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychometricreportsubsection',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='psychometricreportsubsection',
            name='deleted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychometricreportsubsection',
            name='range_value',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='psychometricreportsubsection',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='psychometricreportsubsection',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='psychometricreportsection',
            unique_together={('name', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='psychometricreportsubsection',
            unique_together={('name', 'section', 'deleted')},
        ),
        migrations.AlterModelTable(
            name='psychometricreportsection',
            table='psychometric_report_section',
        ),
        migrations.AlterModelTable(
            name='psychometricreportsubsection',
            table='psychometric_report_subsection',
        ),
    ]
