# Generated by Django 4.1.7 on 2025-01-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0111_psychometricreportsubsection_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='psychometric_report_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='tests.psychometricreportsection', to_field='uid'),
        ),
    ]
