# Generated by Django 4.1.7 on 2025-01-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0112_test_psychometric_report_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychometricreportsubsection',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
