# Generated by Django 4.1.7 on 2025-02-27 08:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0106_alter_accesscodelog_options_and_more'),
        ('tests', '0115_alter_psychometricreportsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPilotuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('targeted_skills', models.TextField()),
                ('objective', models.TextField(blank=True, default=None, null=True)),
                ('industry', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('department', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('key_stakeholders', models.TextField(blank=True, default=None, null=True)),
                ('situation', models.TextField(blank=True, default=None, null=True)),
                ('restart', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.clientuserinfo')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'test_pilot_user',
                'unique_together': {('email', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='TestPilotRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('sent_email', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('test_attempted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('pilotuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testpilotuser')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'db_table': 'test_pilot_record',
            },
        ),
    ]
