# Generated by Django 4.1.7 on 2025-03-05 04:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0116_testpilotuser_testpilotrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpilotrecords',
            name='pilotuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testpilotuser', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='testpilotrecords',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', to_field='uid'),
        ),
        migrations.CreateModel(
            name='TestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('test_case', models.CharField(choices=[('hard_skills', 'hard skills'), ('soft_skills', 'soft skills'), ('report', 'report')], max_length=125)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_tests', to='tests.test', to_field='uid')),
                ('recommended_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_tests', to='tests.test', to_field='uid')),
            ],
            options={
                'db_table': 'test_recommendation',
                'unique_together': {('recommended_test', 'test_case', 'origin_test')},
            },
        ),
    ]
