# Generated by Django 4.1.7 on 2025-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0117_alter_testpilotrecords_pilotuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='personality_model',
            field=models.CharField(blank=True, choices=[('sixteen_factor_discussion', 'sixteen factor discussion'), ('disc_parameter_discussion', 'disc parameter discussion'), ('belbin', 'belbin'), ('blanchard', 'blanchard'), ('big_5', 'big 5')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='personality_model_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
