# Generated by Django 4.1.7 on 2025-03-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0118_test_personality_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpilotuser',
            name='frequency',
            field=models.CharField(choices=[('monday', 'monday'), ('mon_and_thu', 'mon and thu')], default='monday', max_length=255),
        ),
        migrations.AddField(
            model_name='testpilotuser',
            name='preferences',
            field=models.CharField(choices=[('only_soft_skills', 'only soft skills'), ('only_hard_skills', 'only hard skills'), ('mix', 'mix')], default='mix', max_length=255),
        ),
    ]
