# Generated by Django 4.1.7 on 2025-03-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0119_testpilotuser_frequency_testpilotuser_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpilotrecords',
            name='scenario_case_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testpilotuser',
            name='generated_data_for_test',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
