# Generated by Django 4.1.7 on 2025-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0120_testpilotrecords_scenario_case_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpilotuser',
            name='company',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testpilotuser',
            name='history',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testpilotuser',
            name='leaderboard',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testpilotuser',
            name='top_skills',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
