# Generated by Django 4.1.7 on 2025-03-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0121_testpilotuser_company_testpilotuser_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpilotrecords',
            name='intake',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testpilotuser',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
