# Generated by Django 4.1.7 on 2025-04-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0122_testpilotrecords_intake_testpilotuser_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpilotuser',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
