# Generated by Django 4.1.7 on 2025-04-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0123_alter_testpilotuser_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_repeat',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
