# Generated by Django 4.1.7 on 2025-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0124_alter_test_is_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='skill_domain',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
