# Generated by Django 4.1.7 on 2025-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0125_test_skill_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='creator_prompt_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
