# Generated by Django 4.1.7 on 2025-04-24 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0126_test_creator_prompt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('skill_rating', models.BooleanField(default=True)),
                ('culture_rating', models.BooleanField(default=True)),
                ('competency_metrix', models.BooleanField(default=True)),
                ('feedback_summary', models.BooleanField(default=True)),
                ('rating_summary', models.BooleanField(default=True)),
                ('flash_card', models.BooleanField(default=True)),
                ('mindmap', models.BooleanField(default=True)),
                ('speech_metrix', models.BooleanField(default=True)),
                ('powerfiller_words', models.BooleanField(default=True)),
                ('skill_explanation', models.BooleanField(default=True)),
                ('culture_explanation', models.BooleanField(default=True)),
                ('psychometric_culture_rating', models.BooleanField(default=True)),
                ('psychometric_culture_explanation', models.BooleanField(default=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_config', to='tests.test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
