# Generated by Django 4.1.7 on 2025-04-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0127_testreportconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testreportconfig',
            options={'verbose_name': 'Test Report Configuration', 'verbose_name_plural': 'Test Report Configurations'},
        ),
        migrations.AlterUniqueTogether(
            name='testreportconfig',
            unique_together={('test', 'deleted')},
        ),
        migrations.AlterModelTable(
            name='testreportconfig',
            table='test_report_config',
        ),
    ]
