# Generated by Django 4.1.7 on 2025-04-24 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_alter_reportconfig_options_and_more'),
        ('tests', '0128_alter_testreportconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('page_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tab_category', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_mappings', to='users.clientuserinfo')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_mappings', to='tests.test')),
            ],
            options={
                'verbose_name': 'Test Mapping',
                'verbose_name_plural': 'Test Mappings',
                'db_table': 'test_mapping',
                'ordering': ('-id',),
            },
        ),
    ]
