# Generated by Django 4.1.7 on 2025-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0129_testmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmapping',
            name='tab_category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
