# Generated by Django 4.1.7 on 2025-04-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_alter_reportconfig_options_and_more'),
        ('tests', '0130_alter_testmapping_tab_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmapping',
            name='page_name',
            field=models.CharField(blank=True, choices=[('leadership_library', 'leadership library'), ('domain_skills_library', 'domain skills library')], default='leadership_library', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='testmapping',
            unique_together={('test', 'page_name', 'client', 'deleted')},
        ),
    ]
