# Generated by Django 4.1.7 on 2025-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0131_alter_testmapping_page_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='feedback_script_video_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='script_video_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='video_script',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='feedback_video_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testattemptsession',
            name='feedback_video_script',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
