# Generated by Django 4.1.7 on 2025-05-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0132_test_feedback_script_video_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='feedback_video_script_template',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
