# Generated by Django 4.1.7 on 2025-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0133_test_feedback_video_script_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmapping',
            name='tab_sticker',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
