# Generated by Django 4.1.7 on 2025-05-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0135_testmapping_tab_difficulty_testmapping_tab_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='scenario_case',
            field=models.CharField(blank=True, choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling'), ('presentation', 'presentation'), ('dynamic_discussion', 'dynamic discussion'), ('feedback_role_play', 'feedback role play'), ('employee_feedback', 'employee feedback'), ('mcq', 'mcq'), ('pms', 'pms'), ('process_training', 'process training'), ('english_support', 'english support'), ('pitch', 'pitch'), ('assessment', 'assessment'), ('psychometric', 'psychometric'), ('game', 'game'), ('journaling', 'journaling'), ('observation', 'observation'), ('others', 'others')], default='simulation', max_length=255, null=True),
        ),
    ]
