# Generated by Django 4.1.7 on 2025-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0136_alter_test_scenario_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='question_insight',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
