# Generated by Django 4.1.7 on 2025-06-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0137_testquestion_question_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
