# Generated by Django 4.1.7 on 2025-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0138_test_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='instruction_media_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
