# Generated by Django 4.1.7 on 2025-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0139_test_instruction_media_link_alter_test_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='notice_board',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
