# Generated by Django 4.1.7 on 2025-07-11 05:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_alter_clientuserinfo_test_per_month_and_more'),
        ('tests', '0139_test_instruction_media_link_alter_test_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('sticker', models.CharField(blank=True, max_length=55, null=True)),
                ('tests', models.ManyToManyField(blank=True, null=True, related_name='user_test_mappings', to='tests.test')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'User Test Mapping',
                'verbose_name_plural': 'User Test Mappings',
                'db_table': 'user_test_mappings',
                'ordering': ('-id',),
                'unique_together': {('user', 'deleted')},
            },
        ),
    ]
