# Generated by Django 4.1.7 on 2025-07-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0140_test_notice_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='notice_board',
            field=models.TextField(blank=True, default='Note: These are our standard curated simulation scenarios. For deeper learning opportunities using your team and company-specific scenarios, please contact your learning administrator.', null=True),
        ),
    ]
