# Generated by Django 4.1.7 on 2025-07-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0140_usertestmapping'),
        ('tests', '0141_alter_test_notice_board'),
    ]

    operations = [
    ]
