# Generated by Django 4.1.7 on 2025-08-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0142_merge_20250724_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='culture_skills_to_evaluate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
