# Generated by Django 4.1.7 on 2025-08-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0143_test_culture_skills_to_evaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='culture_skills_to_evaluate',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
