# Generated by Django 4.1.7 on 2025-08-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0144_alter_test_culture_skills_to_evaluate'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tag',
            field=models.CharField(blank=True, choices=[('assessment', 'assessment'), ('general', 'general')], default='general', max_length=55, null=True),
        ),
    ]
