# Generated by Django 4.1.7 on 2025-08-24 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_alter_signaturebot_send_bot_transcript'),
        ('tests', '0145_test_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('client', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.clientuserinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('modules_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('module_name', models.CharField(max_length=30)),
                ('CHAPTER_TYPE_CHOICES', models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('VIDEO', 'Video Lesson'), ('TEXT', 'Text Lesson'), ('CHATBOT', 'Chatbot'), ('IMAGE', 'Image')], default='ASSESSMENT', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('embed_link', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='tests.course')),
                ('test', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
