# Generated by Django 4.1.7 on 2025-08-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0145_test_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='que_explanation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
