# Generated by Django 4.1.7 on 2025-08-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0146_testquestion_que_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='explanation_visible',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='score_visible',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
