# Generated by Django 4.1.7 on 2025-08-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0147_test_explanation_visible_test_score_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='score_config',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
