# Generated by Django 4.1.7 on 2025-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0148_testquestion_score_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='score_config',
        ),
        migrations.AddField(
            model_name='test',
            name='score_config',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
