# Generated by Django 4.1.7 on 2025-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0149_remove_testquestion_score_config_test_score_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='generate_feedback',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
