# Generated by Django 4.1.7 on 2025-09-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0150_test_generate_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='generate_feedback',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
