# Generated by Django 4.1.7 on 2025-09-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0146_course_userprogress_module'),
        ('tests', '0151_alter_test_generate_feedback'),
    ]

    operations = [
    ]
