# Generated by Django 4.1.7 on 2025-09-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0152_merge_20250905_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='audio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='CHAPTER_TYPE_CHOICES',
            field=models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('VIDEO', 'Video Lesson'), ('TEXT', 'Text Lesson'), ('CHATBOT', 'Chatbot'), ('IMAGE', 'Image'), ('BOOK', 'Book')], default='ASSESSMENT', max_length=20),
        ),
    ]
