# Generated by Django 4.1.7 on 2025-09-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0153_module_audio_link_alter_module_chapter_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('COURSE', 'Course'), ('LIBRARY', 'Library')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='email_candidate',
            field=models.BooleanField(blank=True, default=True, help_text='Report at End and Email candidate', null=True),
        ),
    ]
