# Generated by Django 4.1.7 on 2025-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0154_course_type_module_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='tag',
            field=models.CharField(default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('COURSE', 'course'), ('LIBRARY', 'library')], default='course', max_length=20),
        ),
    ]
