# Generated by Django 4.1.7 on 2025-09-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0155_module_author_module_tag_alter_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=60),
        ),
    ]
