# Generated by Django 4.1.7 on 2025-09-11 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_alter_clientuserinfo_button_controls'),
        ('tests', '0156_alter_module_module_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='CHAPTER_TYPE_CHOICES',
            new_name='chapter_type',
        ),
        migrations.AlterField(
            model_name='course',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.clientuserinfo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('course', 'Course'), ('library', 'Library')], default='course', max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tests.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='tag',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='tests.course'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='users.user'),
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_started', 'Not Started')], db_index=True, default='not_started', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='tests.module')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='tests.userprogress')),
            ],
            options={
                'db_table': 'module_progress',
                'ordering': ['module__id'],
            },
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_courses', to='users.clientuserinfo')),
                ('courses', models.ManyToManyField(blank=True, related_name='packages', to='tests.course')),
            ],
            options={
                'verbose_name': 'Course Package',
                'verbose_name_plural': 'Course Packages',
                'db_table': 'course_package',
            },
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['status'], name='module_prog_status_9c537a_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['module', 'status'], name='module_prog_module__ca5720_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('user_progress', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='coursepackage',
            unique_together={('client', 'title')},
        ),
    ]
