# Generated by Django 4.1.7 on 2025-09-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0157_rename_chapter_type_choices_module_chapter_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='client',
        ),
    ]
