# Generated by Django 4.1.7 on 2025-09-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0158_remove_course_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'Course User Progress', 'verbose_name_plural': 'Course User Progresses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='tenant_id',
        ),
    ]
