# Generated by Django 4.1.7 on 2025-09-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0159_alter_userprogress_options_remove_course_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepackage',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tests.coursepackage'),
        ),
    ]
