# Generated by Django 4.1.7 on 2025-09-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0160_remove_coursepackage_courses_course_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='package',
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='packages', to='tests.course'),
        ),
    ]
