# Generated by Django 4.1.7 on 2025-09-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0161_remove_course_package_coursepackage_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='list_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='listen_later',
            field=models.BooleanField(default=False),
        ),
    ]
