# Generated by Django 4.1.7 on 2025-09-15 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_alter_clientuserinfo_button_controls'),
        ('tests', '0162_module_like_module_list_name_module_listen_later'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='like',
        ),
        migrations.RemoveField(
            model_name='module',
            name='listen_later',
        ),
        migrations.AlterField(
            model_name='module',
            name='list_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.CreateModel(
            name='ModuleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tests.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_likes', to='users.user')),
            ],
            options={
                'db_table': 'module_likes',
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ModuleForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_for_later', to='tests.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_for_later', to='users.user')),
            ],
            options={
                'db_table': 'module_for_later',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
