# Generated by Django 4.1.7 on 2025-09-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0011_jobaidsession_liked_by'),
        ('tests', '0163_remove_module_like_remove_module_listen_later_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='job_aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to='jobaid.jobaid'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='completed_in_percentage',
            field=models.FloatField(blank=True, default=0.0, help_text='Percentage of module completed', null=True),
        ),
    ]
