# Generated by Django 4.1.7 on 2025-09-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0164_coursepackage_job_aid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='played_audio',
            field=models.FloatField(blank=True, default=0.0, help_text='Percentage of audio played', null=True),
        ),
    ]
