# Generated by Django 4.1.7 on 2025-10-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0165_moduleprogress_played_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='que_marks',
            field=models.IntegerField(default=0),
        ),
    ]
