# Generated by Django 4.1.7 on 2025-10-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0166_testquestion_que_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='tag',
            field=models.CharField(default='General', max_length=55),
        ),
    ]
