# Generated by Django 4.1.7 on 2025-10-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0166_testquestion_que_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_personality_game',
            field=models.BooleanField(default=False),
        ),
    ]
