# Generated by Django 4.1.7 on 2025-10-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0167_alter_module_tag'),
        ('tests', '0167_test_is_personality_game'),
    ]

    operations = [
    ]
