# Generated by Django 4.1.7 on 2025-10-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0168_merge_20251008_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='image_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
