# Generated by Django 4.1.7 on 2025-10-13 09:36

from django.db import migrations, models
import tests.choices


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0169_coursepackage_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='page_config',
            field=models.JSONField(blank=True, default=tests.choices.default_page_config, help_text="Configuration settings for the course package pages. eg: {'show_filters': true, 'show_lists': true, 'show_search': true, 'show_sorting': true}", null=True),
        ),
    ]
