# Generated by Django 4.1.7 on 2025-10-13 09:42

from django.db import migrations, models
import tests.choices


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0170_coursepackage_page_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepackage',
            name='page_config',
            field=models.JSONField(default=tests.choices.default_page_config, help_text="Configuration settings for the course package pages. eg: {'show_filters': true, 'show_lists': true, 'show_search': true, 'show_sorting': true}"),
        ),
    ]
