# Generated by Django 4.1.7 on 2025-10-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0171_alter_coursepackage_page_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='business_outcome',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='emerging_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='implementation_complexity',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='module',
            name='unexpected_outcome',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
