# Generated by Django 4.1.7 on 2025-10-14 11:32

from django.db import migrations, models
import tests.choices


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0172_module_business_outcome_module_emerging_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='function',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='page_config',
            field=models.JSONField(default=tests.choices.default_page_config, help_text="Configuration settings for the course package pages. eg: {'show_filters': 'Industry, Function, Unexpected Outcomes, Implementation Complexity,  Business Outcome,Emerging Players', 'show_lists': true, 'show_search': true}"),
        ),
    ]
