# Generated by Django 4.1.7 on 2025-10-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0173_module_function_alter_coursepackage_page_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'type')},
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
