# Generated by Django 4.1.7 on 2025-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0174_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=255),
        ),
    ]
