# Generated by Django 4.1.7 on 2025-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0175_alter_module_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestmapping',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='user_test_mappings', to='tests.test'),
        ),
    ]
