# Generated by Django 4.1.7 on 2025-11-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0176_alter_usertestmapping_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='implementation_complexity',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='unexpected_outcome',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
