# Generated by Django 4.1.7 on 2025-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0177_alter_module_implementation_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='startup',
            field=models.BooleanField(default=False),
        ),
    ]
