# Generated by Django 4.1.7 on 2025-11-18 06:00

from django.db import migrations, models
import tests.choices


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0178_module_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='key_words',
            field=models.TextField(blank=True, default=None, help_text='Comma-separated keywords for search optimization', null=True),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='page_config',
            field=models.JSONField(default=tests.choices.default_page_config, help_text="Configuration settings for the course package pages. eg: {'show_filters': 'Industry, Function, Unexpected Outcomes, Implementation Complexity,  Business Outcome,Emerging Players, Start Up', 'show_lists': true, 'show_search': true}"),
        ),
    ]
