# Generated by Django 4.1.7 on 2025-11-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0179_module_key_words_alter_coursepackage_page_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='transform_iq',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
