# Generated by Django 4.1.7 on 2025-11-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0181_collection_casemappings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemappings',
            name='tab_type',
        ),
    ]
