# Generated by Django 4.1.7 on 2025-11-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0182_remove_casemappings_tab_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='client',
        ),
    ]
