# Generated by Django 4.1.7 on 2025-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0183_remove_collection_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemappings',
            name='transform_iq',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
