# Generated by Django 4.1.7 on 2025-12-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0017_alter_jobaid_prompt_generation_prompt_and_more'),
        ('tests', '0184_casemappings_transform_iq'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='prompt_job_aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_course_packages', to='jobaid.jobaid'),
        ),
    ]
