# Generated by Django 4.1.7 on 2025-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0185_coursepackage_prompt_job_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='heading',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
