# Generated by Django 4.1.7 on 2025-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0186_collection_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='total_likes',
            field=models.IntegerField(default=0, help_text='Total likes received for the module'),
        ),
    ]
