# Generated by Django 4.1.7 on 2025-12-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0188_casemappings_action_tab_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemappings',
            name='action_tab_info',
        ),
        migrations.AddField(
            model_name='collection',
            name='action_tab_info',
            field=models.JSONField(blank=True, default=None, help_text='{id: "internal-transformation", title: "Internal Transformation Projects", description: "Submit & View Project Themes", icon: <FolderPlus className="w-9 h-9 text-[#00c193]" />, buttons: [ { label: "ALIGN", action: "INTERNAL_TRANSFORMATION_ALIGN" }, { label: "PROPOSE", action: "INTERNAL_TRANSFORMATION_PROPOSE" },],}', null=True),
        ),
    ]
