# Generated by Django 4.1.7 on 2025-12-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0189_remove_casemappings_action_tab_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='iframe_link',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='action_tab_info',
            field=models.JSONField(blank=True, default=None, help_text='always add CONCEPTS prefix in action.  eg: {id: "design-architecture",title: "Design & Architecture Guardrails",description: "Evaluation Heuristics for common cases",icon: "<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#00c193" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3z"/><path d="m9 12 2 2 4-4"/></svg>",buttons: [{ label: "ALIGN", action: "DESIGN_ARCH_GUARDRAILS" }],}', null=True),
        ),
    ]
