# Generated by Django 4.1.7 on 2025-12-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0190_collection_iframe_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattemptsession',
            name='session_user_context',
            field=models.TextField(blank=True, default=None, help_text='it will store user/bot context user will provide before attempting a session.', null=True),
        ),
    ]
