# Generated by Django 4.1.7 on 2026-01-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0191_testattemptsession_session_user_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemappings',
            name='action_name',
            field=models.CharField(blank=True, help_text='Action on the action button for a collection', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='action_tab_info',
            field=models.JSONField(blank=True, default=None, help_text='\n                                       NOTE: Always Match action with the caseMapping.action_name to make it work.\n                                       always add CONCEPTS prefix in action.  \n                                       eg: {id: "design-architecture",\n                                       title: "Design & Architecture Guardrails",\n                                       description: "Evaluation Heuristics for common cases",\n                                       icon: "<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#00c193" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3z"/><path d="m9 12 2 2 4-4"/></svg>",\n                                       buttons: [{ label: "ALIGN", action: "DESIGN_ARCH_GUARDRAILS" }],\n                                       }', null=True),
        ),
    ]
