# Generated by Django 4.1.7 on 2026-01-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0192_casemappings_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='action_tab_info',
            field=models.JSONField(blank=True, default=None, help_text='\n                                       NOTE: Always Match action with the caseMapping.action_name to make it work.\n                                       always add CONCEPTS prefix in action.  \n                                       eg: {\n                                        id: "design-architecture",\n                                        title: "Design & Architecture Guardrails",description: "Evaluation Heuristics for common cases",icon: "<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#00c193" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3z"/><path d="m9 12 2 2 4-4"/></svg>",                                      buttons: [\n                                        { \n                                        label: "ALIGN", \n                                        collection_name: “collecitonnaem”, # it will override box heading of collection\n                                        heading: "which will be shown header of button section", # if heading then it will override collection.heading in UI\n                                        action: "DESIGN_ARCH_GUARDRAILS" # should be matched with ccasemapping.action_name\n                                        }],', null=True),
        ),
    ]
