# Generated by Django 4.1.7 on 2026-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0193_alter_collection_action_tab_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='iframe_subtitle',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='iframe_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
