# Generated by Django 4.1.7 on 2026-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0194_collection_iframe_subtitle_collection_iframe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='card_button_label',
            field=models.JSONField(blank=True, default=None, help_text='for eg: {"description": "TransformIQ", "report": "Report"}', null=True),
        ),
    ]
