# Generated by Django 4.1.7 on 2026-01-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0195_module_card_button_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='card_button_label',
        ),
        migrations.AddField(
            model_name='module',
            name='card_button_config',
            field=models.JSONField(blank=True, default=None, help_text='for eg: {"description": {"show": true, "label": "TransformIQ"}, "report": {"show": true, "label": "TransformIQ"}, "audio_button": {"show": true, "label": ""}}', null=True),
        ),
    ]
