# Generated by Django 4.1.7 on 2026-01-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0142_remove_librarybotconfig_card_button_label_and_more'),
        ('tests', '0196_remove_module_card_button_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleClientLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_likes', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientuserinfo')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.module')),
            ],
        ),
        migrations.AddIndex(
            model_name='moduleclientlike',
            index=models.Index(fields=['module', 'client'], name='tests_modul_module__8b0c0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleclientlike',
            unique_together={('module', 'client')},
        ),
    ]
