# Generated by Django 4.1.7 on 2026-01-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0197_moduleclientlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemappings',
            name='sticker',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='sticker',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
