# Generated by Django 4.1.7 on 2026-02-10 06:53

from django.db import migrations, models
import tests.choices


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0198_casemappings_sticker_module_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepackage',
            name='page_config',
            field=models.JSONField(default=tests.choices.default_page_config, help_text="Configuration settings for the course package pages. eg: {'heading': 'xyz','show_filters': 'Industry, Function, Unexpected Outcomes, Implementation Complexity,  Business Outcome,Emerging Players, Start Up', 'show_lists': true, 'show_search': true}"),
        ),
    ]
