# Generated by Django 4.1.7 on 2026-03-10 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0147_clientresource_label'),
        ('tests', '0199_alter_coursepackage_page_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='started', max_length=20)),
                ('completion_percentage', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('case_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_sessions', to='tests.casemappings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_sessions', to='users.user')),
            ],
            options={
                'verbose_name': 'Concept Session',
                'verbose_name_plural': 'Concept Sessions',
                'db_table': 'concept_session',
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddIndex(
            model_name='conceptsession',
            index=models.Index(fields=['user', 'case_mapping'], name='concept_ses_user_id_9275e1_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptsession',
            index=models.Index(fields=['user', 'status'], name='concept_ses_user_id_1f09e7_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptsession',
            index=models.Index(fields=['case_mapping'], name='concept_ses_case_ma_da8fdd_idx'),
        ),
        migrations.AddConstraint(
            model_name='conceptsession',
            constraint=models.UniqueConstraint(fields=('user', 'case_mapping', 'is_active'), name='unique_active_session'),
        ),
    ]
