# Generated by Django 4.1.7 on 2026-03-30 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobaid', '0029_jobaid_session_voting_enabled_alter_jobaid_labels'),
        ('tests', '0200_conceptsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptsession',
            name='jobaid_attempted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_sessions', to='jobaid.jobaidsession'),
        ),
        migrations.AddField(
            model_name='conceptsession',
            name='meta_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='conceptsession',
            name='case_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concept_sessions', to='tests.casemappings'),
        ),
    ]
