# Generated by Django 4.1.7 on 2026-03-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0201_conceptsession_jobaid_attempted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptsession',
            name='case_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_sessions', to='tests.module'),
        ),
    ]
