# Generated by Django 4.1.7 on 2023-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTypeTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('test_code', models.CharField(blank=True, max_length=64, null=True)),
                ('case_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'specail_case_tests',
            },
        ),
    ]
