# Generated by Django 4.1.7 on 2023-09-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_specialtypetests'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtypetests',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
