# Generated by Django 4.1.7 on 2024-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_specialtypetests_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('mentor_id', models.CharField(max_length=255)),
                ('mentee_ids', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'mentor_details',
            },
        ),
        migrations.CreateModel(
            name='SessionNotesRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('mentor_id', models.CharField(max_length=255)),
                ('mentee_id', models.CharField(max_length=255)),
                ('session_notes', models.TextField(blank=True, default=None, null=True)),
                ('recommendations', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'session_notes_and_recommendations',
            },
        ),
    ]
