# Generated by Django 4.1.7 on 2024-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_mentordetails_sessionnotesrecommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionnotesrecommendations',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
