# Generated by Django 4.1.7 on 2024-01-12 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_alter_sessionnotesrecommendations_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('participant_id', models.CharField(max_length=255)),
                ('bot_id', models.CharField(max_length=255)),
                ('participant_qna', models.JSONField(blank=True, default=None, null=True)),
                ('is_positive', models.BooleanField(default=False, null=True)),
                ('qna_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bot_qna',
            },
        ),
    ]
