# Generated by Django 4.1.7 on 2024-01-12 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_botqna'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('bot_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('feedback_given', models.IntegerField(blank=True, default=0, null=True)),
                ('feedback_recieved', models.IntegerField(blank=True, default=0, null=True)),
                ('transcript_email_sent', models.IntegerField(blank=True, default=0, null=True)),
                ('transcript_email_recieved', models.IntegerField(blank=True, default=0, null=True)),
                ('chat_attempted', models.IntegerField(blank=True, default=0, null=True)),
                ('interaction_attempted', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'user_action_info',
            },
        ),
    ]
