# Generated by Django 4.1.7 on 2024-01-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_useractioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='botqna',
            name='fitment_score',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
