# Generated by Django 4.1.7 on 2024-01-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_botqna_fitment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('bot_type', models.CharField(choices=[('avatar_bot', 'avatar bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot')], max_length=255)),
                ('profile_pic_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('profile_type', models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee')], max_length=255)),
                ('description', models.TextField()),
                ('experience', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('favourite_simulation_codes', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('booked', 'booked')], max_length=255)),
                ('bot_url', models.TextField()),
                ('feedback_wall', models.TextField(blank=True, default=None, null=True)),
                ('is_visible', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'directory_information',
            },
        ),
    ]
