# Generated by Django 4.1.7 on 2024-01-25 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_botqna_fitment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('strengths', models.TextField(blank=True, default=0, null=True)),
                ('weakness', models.TextField(blank=True, default=0, null=True)),
                ('opportunities', models.TextField(blank=True, default=0, null=True)),
                ('threats', models.TextField(blank=True, default=0, null=True)),
                ('key_focus_areas', models.TextField(blank=True, default=0, null=True)),
                ('goals', models.TextField(blank=True, default=0, null=True)),
                ('priorities', models.TextField(blank=True, default=0, null=True)),
                ('learning_histories', models.TextField(blank=True, default=0, null=True)),
                ('key_skills', models.TextField(blank=True, default=0, null=True)),
                ('skill_gap_for_development', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('leadership_skill_focus_area', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('book_recommendations', models.TextField(blank=True, default=0, null=True)),
                ('course_recommendations', models.TextField(blank=True, default=0, null=True)),
                ('recommended_hbr', models.TextField(blank=True, default=0, null=True)),
                ('recommended_ted_talk', models.TextField(blank=True, default=0, null=True)),
                ('recommended_scenarios', models.JSONField(blank=True, default=None, null=True)),
                ('report', models.TextField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'user_idp_report',
            },
        ),
    ]
