# Generated by Django 4.1.7 on 2024-01-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_directorypageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypageinfo',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
