# Generated by Django 4.1.7 on 2024-01-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_directorypageinfo_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorypageinfo',
            name='bot_url',
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='avatar_bot_id',
            field=models.CharField(default='avatar', max_length=400),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='avatar_bot_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='avatar_snippit',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='profile_id',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='skills',
            field=models.CharField(default='communication skills', max_length=400),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='feedback_wall',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='profile_type',
            field=models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee'), ('coach-mentor', 'coach mentor'), ('skill_bot', 'skill bot')], max_length=255),
        ),
    ]
