# Generated by Django 4.1.7 on 2024-01-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_useridp'),
        ('utilities', '0011_remove_directorypageinfo_bot_url_and_more'),
    ]

    operations = [
    ]
