# Generated by Django 4.1.7 on 2024-01-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_merge_20240125_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridp',
            name='user_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
