# Generated by Django 4.1.7 on 2024-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0013_useridp_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypageinfo',
            name='avatar_bot_id',
            field=models.CharField(blank=True, default='avatar', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='profile_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='skills',
            field=models.CharField(blank=True, default='communication skills', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('booked', 'booked')], default='available', max_length=255, null=True),
        ),
    ]
