# Generated by Django 4.1.7 on 2024-01-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0015_useridp_success_alter_useridp_book_recommendations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorypageinfo',
            old_name='favourite_simulation_codes',
            new_name='expertise',
        ),
    ]
