# Generated by Django 4.1.7 on 2024-02-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0016_rename_favourite_simulation_codes_directorypageinfo_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridp',
            name='total_scenarios_created',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='useridp',
            name='leadership_skill_focus_area',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useridp',
            name='skill_gap_for_development',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useridp',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
