# Generated by Django 4.1.7 on 2024-02-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0017_useridp_total_scenarios_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractioninfo',
            name='avatar_bot_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='avatar_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='session_notes_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='subject_matter_bot_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='subject_matter_bot_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
