# Generated by Django 4.1.7 on 2024-02-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0018_useractioninfo_avatar_bot_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioCreationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('creator_id', models.CharField(max_length=255)),
                ('input', models.TextField(blank=True, default=None, null=True)),
                ('output', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(max_length=255)),
                ('reason_of_failure', models.TextField(blank=True, default=None, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scenario_creation_details',
            },
        ),
    ]
