# Generated by Django 4.1.7 on 2024-02-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0019_scenariocreationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='botqna',
            name='intake_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
