# Generated by Django 4.1.7 on 2024-02-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0019_scenariocreationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridp',
            name='learning_communities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
