# Generated by Django 4.1.7 on 2024-02-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0020_botqna_intake_summary'),
        ('utilities', '0020_useridp_learning_communities'),
    ]

    operations = [
    ]
