# Generated by Django 4.1.7 on 2024-02-29 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0021_merge_20240224_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCoacheeJoiningPreviledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('can_join_as', models.CharField(choices=[('coach', 'coach'), ('mentor', 'mentor'), ('coachee', 'coachee'), ('mentee', 'mentee')], default='coachee', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
