# Generated by Django 4.1.7 on 2024-02-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0022_coachcoacheejoiningpreviledge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coachcoacheejoiningpreviledge',
            unique_together={('email', 'client_name', 'tenant_id')},
        ),
        migrations.AlterModelTable(
            name='coachcoacheejoiningpreviledge',
            table='coach_coachee_joining_previledge',
        ),
    ]
