# Generated by Django 4.1.7 on 2024-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0023_alter_coachcoacheejoiningpreviledge_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypageinfo',
            name='bot_type',
            field=models.CharField(choices=[('avatar_bot', 'avatar bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot')], max_length=255),
        ),
    ]
