# Generated by Django 4.1.7 on 2024-03-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0024_alter_directorypageinfo_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypageinfo',
            name='custom_user_bot_url',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
