# Generated by Django 4.1.7 on 2024-03-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0025_directorypageinfo_custom_user_bot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypageinfo',
            name='profile_type',
            field=models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee'), ('coach-mentor', 'coach mentor'), ('skill_bot', 'skill bot'), ('coachbots', 'coachbots')], max_length=255),
        ),
    ]
