# Generated by Django 4.1.7 on 2024-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0026_alter_directorypageinfo_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypageinfo',
            name='custom_user_bot_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
