# Generated by Django 4.1.7 on 2024-03-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0027_alter_directorypageinfo_custom_user_bot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botqna',
            name='bot_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
