# Generated by Django 4.1.7 on 2024-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0028_alter_botqna_bot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botqna',
            name='is_anonymous',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
