# Generated by Django 4.1.7 on 2024-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0029_botqna_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypageinfo',
            name='timer_info',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='profile_type',
            field=models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee'), ('coach-mentor', 'coach mentor'), ('skill_bot', 'skill bot'), ('coachbots', 'coachbots'), ('external', 'external')], max_length=255),
        ),
    ]
