# Generated by Django 4.1.7 on 2024-03-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0030_directorypageinfo_timer_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorypageinfo',
            name='timer_info',
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='time_value_in_days',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='timer_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='timer_reset',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='avatar_bot_id',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='profile_type',
            field=models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee'), ('coach-mentor', 'coach mentor'), ('skill_bot', 'skill bot'), ('coachbots', 'coachbots'), ('external', 'external'), ('icons_by_ai', 'icons by ai')], max_length=255),
        ),
    ]
