# Generated by Django 4.1.7 on 2024-03-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0031_alter_directorypageinfo_profile_type'),
        ('utilities', '0031_remove_directorypageinfo_timer_info_and_more'),
    ]

    operations = [
    ]
