# Generated by Django 4.1.7 on 2024-03-13 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0032_merge_20240313_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('bot_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('interacted_on', models.DateField()),
                ('num_of_clicked_button', models.IntegerField(blank=True, default=0, null=True)),
                ('attempted_bot_questions', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_bot_sessions', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'bot_engagements',
                'unique_together': {('tenant_id', 'deleted', 'bot_id', 'user_id', 'interacted_on')},
            },
        ),
    ]
