# Generated by Django 4.1.7 on 2024-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0033_botengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypageinfo',
            name='visual_tag',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
