# Generated by Django 4.1.7 on 2024-03-18 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0034_directorypageinfo_visual_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('bot_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.CharField(max_length=255)),
                ('sent_to', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'email_sent_details',
            },
        ),
    ]
