# Generated by Django 4.1.7 on 2024-03-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0035_emailsentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnotesrecommendations',
            name='simulation_codes',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
