# Generated by Django 4.1.7 on 2024-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0037_directorypageinfo_custom_user_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypageinfo',
            name='profile_type',
            field=models.CharField(choices=[('coach', 'coach'), ('coachee', 'coachee'), ('mentor', 'mentor'), ('mentee', 'mentee'), ('coach-mentor', 'coach mentor'), ('skill_bot', 'skill bot'), ('coachbots', 'coachbots'), ('external', 'external'), ('icons_by_ai', 'icons by ai'), ('knowledge_bot', 'knowledge bot'), ('customer_avatar', 'customer avatar')], max_length=255),
        ),
    ]
