# Generated by Django 4.1.7 on 2024-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0038_alter_directorypageinfo_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypageinfo',
            name='ai_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
