# Generated by Django 4.1.7 on 2024-04-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0039_directorypageinfo_ai_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypageinfo',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
