# Generated by Django 4.1.7 on 2024-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0040_alter_directorypageinfo_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypageinfo',
            name='_previous_is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
