# Generated by Django 4.1.7 on 2024-06-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0042_directorypageinfo_deep_dive_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractioninfo',
            unique_together={('tenant_id', 'deleted', 'user_id')},
        ),
    ]
