# Generated by Django 4.1.7 on 2024-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0043_alter_useractioninfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractioninfo',
            name='avatar_chat_attempted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='deep_dive_bot_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='deep_dive_chat_attempted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='feedback_bot_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='knowledge_bot_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='knowledge_chat_attempted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='subject_matter_chat_attempted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
