# Generated by Django 4.1.7 on 2024-07-24 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0044_useractioninfo_avatar_chat_attempted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMMappingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('bot_type', models.CharField(max_length=255)),
                ('llm1', models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='gemini', max_length=255, null=True)),
                ('llm2', models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='anthropic', max_length=255, null=True)),
                ('llm3', models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='gpt', max_length=255, null=True)),
            ],
            options={
                'db_table': 'llm_mapping_table',
                'unique_together': {('bot_type', 'tenant_id')},
            },
        ),
    ]
