# Generated by Django 4.1.7 on 2024-07-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0045_llmmappingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmappingtable',
            name='bot_type',
            field=models.CharField(choices=[('avatar_bot', 'avatar bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], max_length=255),
        ),
    ]
