# Generated by Django 4.1.7 on 2024-08-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0047_globalprompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalprompts',
            name='resourse_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='globalprompts',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
