# Generated by Django 4.1.7 on 2024-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0049_globalsysteminstructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'widgets',
            },
        ),
    ]
