# Generated by Django 4.1.7 on 2024-08-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0050_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='allow_audio_interaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widgets',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgets',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widgets',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
