# Generated by Django 4.1.7 on 2024-08-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0050_alter_globalprompts_resourse_type_and_more'),
        ('utilities', '0051_widgets_allow_audio_interaction_widgets_client_id_and_more'),
    ]

    operations = [
    ]
