# Generated by Django 4.1.7 on 2024-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0052_merge_20240812_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
