# Generated by Django 4.1.7 on 2024-10-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0053_widgets_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorypageinfo',
            name='deep_dive_bot_id',
        ),
        migrations.RemoveField(
            model_name='directorypageinfo',
            name='deep_dive_bot_url',
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='subject_specific_bot_id',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='subject_specific_bot_snippit',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='subject_specific_bot_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='subject_specific_bot_ids',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useractioninfo',
            name='subject_specific_chat_attempted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='directorypageinfo',
            name='bot_type',
            field=models.CharField(blank=True, choices=[('avatar_bot', 'avatar bot'), ('subject_specific_bot', 'subject specific bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalprompts',
            name='resourse_type',
            field=models.CharField(choices=[('avatar_bot', 'avatar bot'), ('subject_specific_bot', 'subject specific bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], max_length=255),
        ),
        migrations.AlterField(
            model_name='globalsysteminstructions',
            name='resourse_type',
            field=models.CharField(choices=[('avatar_bot', 'avatar bot'), ('subject_specific_bot', 'subject specific bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='bot_type',
            field=models.CharField(choices=[('avatar_bot', 'avatar bot'), ('subject_specific_bot', 'subject specific bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], max_length=255),
        ),
    ]
