# Generated by Django 4.1.7 on 2024-10-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0054_remove_directorypageinfo_deep_dive_bot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypageinfo',
            name='deep_dive_bot_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='directorypageinfo',
            name='deep_dive_bot_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
