# Generated by Django 4.1.7 on 2024-10-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0055_directorypageinfo_deep_dive_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypageinfo',
            name='subject_specific_bot_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
