# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0056_alter_directorypageinfo_subject_specific_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botengagement',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botqna',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalprompts',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalsysteminstructions',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractioninfo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useridp',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
