# Generated by Django 4.1.7 on 2025-08-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0057_alter_botengagement_deleted_alter_botqna_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmmappingtable',
            options={'verbose_name': 'LLM Mapping', 'verbose_name_plural': 'LLM Mappings'},
        ),
        migrations.RemoveField(
            model_name='llmmappingtable',
            name='llm1',
        ),
        migrations.RemoveField(
            model_name='llmmappingtable',
            name='llm2',
        ),
        migrations.RemoveField(
            model_name='llmmappingtable',
            name='llm3',
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='bot_type',
            field=models.CharField(choices=[('avatar_bot', 'avatar bot'), ('subject_specific_bot', 'subject specific bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], help_text='Select the bot type this mapping applies to.', max_length=255),
        ),
        migrations.CreateModel(
            name='LLMMappingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], help_text='LLM provider (e.g., gemini, anthropic, gpt)', max_length=255)),
                ('model', models.CharField(help_text='Exact model name (e.g., gemini-2.5-flash)', max_length=255)),
                ('order', models.PositiveSmallIntegerField(help_text='Order in which this LLM is called')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llms', to='utilities.llmmappingtable')),
            ],
            options={
                'verbose_name': 'LLM Mapping Item',
                'verbose_name_plural': 'LLM Mapping Items',
                'db_table': 'llm_mapping_item',
                'ordering': ['order'],
                'unique_together': {('mapping', 'order')},
            },
        ),
    ]
