# Generated by Django 4.1.7 on 2025-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0058_alter_llmmappingtable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmappingtable',
            name='llm1',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='gemini', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='llmmappingtable',
            name='llm2',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='anthropic', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='llmmappingtable',
            name='llm3',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='gpt', max_length=255, null=True),
        ),
    ]
