# Generated by Django 4.1.7 on 2025-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0059_llmmappingtable_llm1_llmmappingtable_llm2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmmappingtable',
            options={},
        ),
        migrations.AddField(
            model_name='llmmappingtable',
            name='llm1_model',
            field=models.CharField(blank=True, default='gemini-2', help_text='Model names (comma sperated order wise) for LLM 1.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='llmmappingtable',
            name='llm2_model',
            field=models.CharField(blank=True, default='claude-3', help_text='Model names (comma sperated order wise) for LLM 2.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='llmmappingtable',
            name='llm3_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', help_text='Model names (comma sperated order wise) for LLM 3.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='llm1',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='gemini', help_text='First preference LLM provider.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='llm2',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='anthropic', help_text='Second preference LLM provider.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='llm3',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='gpt', help_text='Third preference LLM provider.', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='LLMMappingItem',
        ),
    ]
