# Generated by Django 4.1.7 on 2025-08-12 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0060_alter_llmmappingtable_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmmappingtable',
            name='llm1_model',
        ),
        migrations.RemoveField(
            model_name='llmmappingtable',
            name='llm2_model',
        ),
        migrations.RemoveField(
            model_name='llmmappingtable',
            name='llm3_model',
        ),
        migrations.CreateModel(
            name='LLMMappingModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('llm_type', models.CharField(choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='gemini', max_length=55)),
                ('model_order', models.CharField(blank=True, default='gpt-4o-mini', help_text='Model names (comma separated, in order)', max_length=255, null=True)),
                ('mapping', models.ForeignKey(help_text='Link to the LLM Mapping Table entry.', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='utilities.llmmappingtable')),
            ],
            options={
                'db_table': 'llm_mapping_models',
            },
        ),
    ]
