# Generated by Django 4.1.7 on 2025-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0061_remove_llmmappingtable_llm1_model_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='llmmappingtable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='llmmappingtable',
            name='feature_type',
            field=models.CharField(blank=True, choices=[('scenario_generation', 'Scenario Generation')], default=None, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='llmmappingtable',
            unique_together={('bot_type', 'tenant_id', 'feature_type')},
        ),
    ]
