# Generated by Django 4.1.7 on 2025-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0062_alter_llmmappingtable_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='llmmappingtable',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='bot_type',
            field=models.CharField(blank=True, choices=[('avatar_bot', 'avatar bot'), ('subject_specific_bot', 'subject specific bot'), ('feedback_bot', 'feedback bot'), ('subject_matter_bot', 'subject matter bot'), ('helper_bot', 'helper bot'), ('coachbots', 'coachbots'), ('user_bot', 'user bot'), ('deep_dive', 'deep dive')], default=None, help_text='Select the bot type this mapping applies to.', max_length=255, null=True),
        ),
    ]
