# Generated by Django 4.1.7 on 2025-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0063_alter_llmmappingtable_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmappingmodels',
            name='llm_type',
            field=models.CharField(choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini'), ('caching_anthropic', 'caching anthropic')], default='gemini', max_length=55),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='llm1',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini'), ('caching_anthropic', 'caching anthropic')], default='gemini', help_text='First preference LLM provider.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='llm2',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini'), ('caching_anthropic', 'caching anthropic')], default='anthropic', help_text='Second preference LLM provider.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llmmappingtable',
            name='llm3',
            field=models.CharField(blank=True, choices=[('gpt', 'gpt'), ('anthropic', 'anthropic'), ('gemini', 'gemini'), ('caching_anthropic', 'caching anthropic')], default='gpt', help_text='Third preference LLM provider.', max_length=255, null=True),
        ),
    ]
