# Generated by Django 4.1.7 on 2023-05-23 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillsRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.PositiveSmallIntegerField(default=0)),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("candidate_id", models.CharField(db_index=True, max_length=255)),
                ("teamwork_score", models.FloatField(blank=True, default=0, null=True)),
                (
                    "teamwork_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "leadership_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "leadership_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "people_management_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "people_management_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "conflict_management_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "conflict_management_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "negotiation_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "negotiation_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "strategic_thinking_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "strategic_thinking_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "project_management_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "project_management_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "time_management_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "time_management_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "adaptability_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "adaptability_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "engagement_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "engagement_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("empathy_score", models.FloatField(blank=True, default=0, null=True)),
                (
                    "empathy_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "communication_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "communication_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "confidence_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "confidence_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("clarity_score", models.FloatField(blank=True, default=0, null=True)),
                (
                    "clarity_question_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "total_questions_attempted",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "total_tests_attempted",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "db_table": "skills_rating",
            },
        ),
        migrations.CreateModel(
            name="CustomRatingForLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.PositiveSmallIntegerField(default=0)),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(db_index=True, max_length=255)),
                ("required_rating", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "custom_rating_for_labels",
                "unique_together": {("tenant_id", "label", "deleted")},
            },
        ),
    ]
