# Generated by Django 4.1.7 on 2023-05-25 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillsRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.PositiveSmallIntegerField(default=0)),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("participant_id", models.CharField(db_index=True, max_length=255)),
                ("skills_info", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "total_questions_attempted",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "total_tests_attempted",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "db_table": "skills_rating",
                "unique_together": {("participant_id", "tenant_id", "deleted")},
            },
        ),
        migrations.CreateModel(
            name="CustomRatingForLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.PositiveSmallIntegerField(default=0)),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(db_index=True, max_length=255)),
                ("required_rating", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "custom_rating_for_labels",
                "unique_together": {("tenant_id", "label", "deleted")},
            },
        ),
    ]
