# Generated by Django 4.1.7 on 2023-05-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillsrating',
            unique_together={('tenant_id', 'participant_id', 'deleted')},
        ),
    ]
