# Generated by Django 4.1.7 on 2023-05-25 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skillsrating_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('display', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'skills_index',
                'unique_together': {('tenant_id', 'name', 'deleted')},
            },
        ),
    ]
