# Generated by Django 4.1.7 on 2023-06-02 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0003_skillindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.PositiveSmallIntegerField(default=0)),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                (
                    "custom_rating",
                    models.JSONField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "db_table": "custom_rating",
                "unique_together": {("tenant_id", "deleted")},
            },
        ),
        migrations.DeleteModel(
            name="CustomRatingForLabels",
        ),
    ]
