# Generated by Django 4.1.7 on 2024-01-17 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_customrating_delete_customratingforlabels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicsAndPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('input_vars', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'characteristics_and_prompts',
                'unique_together': {('tenant_id', 'deleted')},
            },
        ),
    ]
