# Generated by Django 4.1.7 on 2024-01-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_characteristicsandprompts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristicsandprompts',
            unique_together={('uid', 'deleted', 'tenant_id')},
        ),
    ]
