# Generated by Django 4.1.7 on 2024-01-18 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_characteristicsandprompts_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristicsandprompts',
            old_name='prompt',
            new_name='negitive_prompt',
        ),
        migrations.AlterUniqueTogether(
            name='characteristicsandprompts',
            unique_together={('uid', 'deleted', 'tenant_id', 'name')},
        ),
        migrations.AddField(
            model_name='characteristicsandprompts',
            name='positive_prompt',
            field=models.TextField(default="Prompt"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='characteristicsandprompts',
            name='input_vars',
        ),
    ]
