# Generated by Django 4.1.7 on 2024-06-27 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_rename_prompt_characteristicsandprompts_negitive_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencySkillAndClientMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('competency_skill', models.CharField(max_length=255)),
                ('prompts', models.TextField()),
                ('output', models.TextField()),
            ],
            options={
                'db_table': 'competency_skill_and_client_mapping',
                'unique_together': {('deleted', 'tenant_id', 'client_id', 'competency_skill')},
            },
        ),
    ]
