# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_competencyskillandclientmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicsandprompts',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competencyskillandclientmapping',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customrating',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skillindex',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skillsrating',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
