# Generated by Django 4.1.7 on 2025-05-28 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_alter_characteristicsandprompts_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureMapSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('skill', models.CharField(max_length=100, verbose_name='Cultural Skill Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('skill_type', models.CharField(choices=[('ocean_model', 'ocean model'), ('communication_skills', 'communication skills'), ('workspace_skills', 'workspace skills')], max_length=50, verbose_name='Skill Type')),
                ('evaluation_criteria', models.JSONField(blank=True, default={}, null=True, verbose_name='Evaluation Criteria')),
                ('test_type', models.CharField(choices=[('simulation', 'simulation'), ('role_play', 'role play'), ('interview', 'interview'), ('group_meeting', 'group meeting'), ('email', 'email'), ('1:1 meeting', 'one on one meeting'), ('case_study', 'case study'), ('counseling', 'counseling'), ('presentation', 'presentation'), ('dynamic_discussion', 'dynamic discussion'), ('feedback_role_play', 'feedback role play'), ('employee_feedback', 'employee feedback'), ('mcq', 'mcq'), ('pms', 'pms'), ('process_training', 'process training'), ('english_support', 'english support'), ('pitch', 'pitch'), ('assessment', 'assessment'), ('psychometric', 'psychometric'), ('game', 'game'), ('journaling', 'journaling'), ('observation', 'observation')], max_length=30, verbose_name='Test Type')),
            ],
            options={
                'db_table': 'culture_map_skills',
            },
        ),
    ]
