# Generated by Django 4.1.7 on 2026-05-21 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0152_user_secret_code_alter_clientuserinfo_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('provider', models.CharField(choices=[('microsoft', 'Microsoft'), ('google', 'Google')], help_text="The SSO provider (e.g., 'microsoft', 'google')", max_length=50)),
                ('provider_id', models.CharField(help_text='Stable ID from provider (e.g., oid from Entra)', max_length=255)),
                ('tid', models.CharField(blank=True, help_text='Multi-tenant ID from provider (e.g., tid from Entra)', max_length=255, null=True)),
                ('email', models.EmailField(help_text='Last seen email from provider', max_length=255)),
                ('raw_claims', models.JSONField(blank=True, default=dict, help_text='Full decoded claims for debugging')),
                ('first_login', models.DateTimeField(auto_now_add=True, help_text='Timestamp of first login with this provider')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of most recent login')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_providers', to='users.user')),
            ],
            options={
                'db_table': 'sso_user_identity_provider',
            },
        ),
        migrations.AddIndex(
            model_name='useridentityprovider',
            index=models.Index(fields=['tid', 'provider', 'provider_id'], name='sso_user_id_tid_1dd7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='useridentityprovider',
            index=models.Index(fields=['tid', 'email'], name='sso_user_id_tid_4a6748_idx'),
        ),
        migrations.AddIndex(
            model_name='useridentityprovider',
            index=models.Index(fields=['user_id'], name='sso_user_id_user_id_3655d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useridentityprovider',
            unique_together={('tid', 'provider', 'provider_id')},
        ),
    ]
