# Generated by Django 4.1.7 on 2023-06-12 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortenerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('long_url_hash', models.CharField(max_length=300)),
                ('long_url', models.CharField(max_length=500)),
                ('short_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'url_shortener_map',
                'unique_together': {('long_url_hash', 'tenant_id', 'deleted')},
            },
        ),
    ]
