# Generated by Django 4.1.7 on 2023-06-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenermap',
            name='long_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='urlshortenermap',
            name='long_url_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='urlshortenermap',
            name='short_url',
            field=models.CharField(max_length=255),
        ),
    ]
