# Generated by Django 4.1.7 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_alter_urlshortenermap_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenermap',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
