# Generated by Django 4.1.7 on 2026-04-01 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0149_clientresource_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.CharField(help_text="Friendly label, e.g. 'Production key'", max_length=120)),
                ('prefix', models.CharField(editable=False, max_length=10)),
                ('hashed_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for non-expiring key', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=255)),
                ('rate_limit_tier', models.CharField(choices=[('low', 'Low (60 req/min)'), ('medium', 'Medium (300 req/min)'), ('high', 'High (1000 req/min)'), ('custom', 'Custom')], default='medium', max_length=10)),
                ('custom_rate_limit', models.IntegerField(blank=True, help_text="Requests per minute — only used when tier is 'custom'", null=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text="Empty list = all IPs allowed. E.g. ['192.168.1.1', '10.0.0.0/8']")),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, help_text='User/email who created this key', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='users.clientuserinfo')),
            ],
            options={
                'verbose_name': 'Client API Key',
                'verbose_name_plural': 'Client API Keys',
                'db_table': 'client_api_keys',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_ms', models.IntegerField(default=0, help_text='Response time in ms')),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='client_apis.clientapikey')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to='users.clientuserinfo')),
            ],
            options={
                'db_table': 'api_key_usage_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['api_key', 'timestamp'], name='api_key_usa_api_key_dede0b_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['client', 'timestamp'], name='api_key_usa_client__66cead_idx'),
        ),
    ]
