# Generated by Django 4.1.7 on 2026-05-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapikey',
            name='created_by',
            field=models.CharField(blank=True, help_text='email who created this key', max_length=255),
        ),
    ]
